const ROLE_LEVELS = {
  r1: 1,
  r2: 2,
  r3: 3,
  r4: 4,
  r5: 4,
  r6: 5,
  r7: 6,
};

const USER_SCOPES = {
  ACCESSIBLE: "accessible",
  ASSIGNABLE: "assignable",
};

const PERMISSIONS = {
  ASSIGN_TASK: "can_assign_tasks",
  TRANSFER_TASK: "transfer_task",
  APPROVE_COMPLETED_TASK: "approve_completed_task",
  SELF_APPROVE: "self_approve",
  APPROVE_QUALITY: "can_approve_quality",
  CHANGE_FIXTURE_STAGE: "change_fixture_stage",
  DELETE_WBS_BATCH: "delete_wbs_batch",
  REOPEN_FIXTURE_STAGE: "reopen_fixture_stage",
  MANIPULATE_FIXTURE_STAGE: "manipulate_fixture_stage",
  VIEW_SELF_TASKS: "can_view_self_tasks",
  VIEW_ALL_TASKS: "can_view_all_tasks",
  CREATE_TASK: "can_create_task",
  EDIT_TASK: "can_edit_task",
  DELETE_TASK: "can_delete_task",
  UPLOAD_PROOFS: "can_upload_proofs",
  UPLOAD_LEGACY_DESIGN_DATA: "upload_legacy_design_data",
  UPLOAD_NATIVE_DESIGN_DATA: "upload_native_design_data",
  MANAGE_USERS: "can_manage_users",
  CREATE_USER: "can_create_user",
  EDIT_USER: "can_edit_user",
  ACTIVATE_USER: "can_activate_user",
  MANAGE_ROLES: "can_manage_roles",
  MANAGE_WORKFLOWS: "can_manage_workflows",
  MANAGE_DEPARTMENTS: "can_manage_departments",
  MANAGE_SHIFTS: "can_manage_shifts",
  MANAGE_MACHINES: "can_manage_machines",
  MANAGE_KPIS: "can_manage_kpis",
  MANAGE_ESCALATION_RULES: "can_manage_escalation_rules",
  VIEW_REPORTS: "can_view_reports",
  EXPORT_REPORTS: "can_export_reports",
  
  // New Strict Analytics Permissions
  VIEW_SELF_ANALYTICS: "view_self_analytics",
  VIEW_DEPARTMENT_ANALYTICS: "view_department_analytics",
  VIEW_ALL_DEPARTMENTS_ANALYTICS: "view_all_departments_analytics",
  VIEW_ALL_USERS_ANALYTICS: "view_all_users_analytics",
  
  VIEW_REWORK_ANALYTICS: "view_rework_analytics",
  VIEW_DEADLINE_ANALYTICS: "view_deadline_analytics",
  VIEW_EFFICIENCY_ANALYTICS: "view_efficiency_analytics",
  VIEW_WORKFLOW_HEALTH_ANALYTICS: "view_workflow_health",
  VIEW_PREDICTIVE_ANALYTICS: "view_predictive_analytics",
};

const PERMISSION_DEFINITIONS = [
  [PERMISSIONS.ASSIGN_TASK, "Assign Task", "Allows assigning tasks to other users."],
  [PERMISSIONS.TRANSFER_TASK, "Transfer Task", "Allows transferring Design stage work while preserving contribution history."],
  [PERMISSIONS.APPROVE_COMPLETED_TASK, "Approve Completed Task", "Allows approving completed non-quality task submissions."],
  [PERMISSIONS.SELF_APPROVE, "Self Approve", "Allows a user to approve their own task when they already have the relevant approval permission."],
  [PERMISSIONS.APPROVE_QUALITY, "Approve Quality", "Allows performing quality-stage approval."],
  [PERMISSIONS.CHANGE_FIXTURE_STAGE, "Change Fixture Stage", "Allows controlled fixture stage transitions."],
  [PERMISSIONS.DELETE_WBS_BATCH, "Delete WBS Batch", "Allows deleting owned WBS upload batches subject to ownership controls."],
  [PERMISSIONS.REOPEN_FIXTURE_STAGE, "Reopen Fixture Stage", "Allows reopening a completed fixture stage with revision history."],
  [PERMISSIONS.MANIPULATE_FIXTURE_STAGE, "Manipulate Fixture Stage", "Allows legacy-only manual fixture stage correction."],
  [PERMISSIONS.VIEW_SELF_TASKS, "View Self Tasks Only", "Allows viewing only tasks assigned to self or created by self."],
  [PERMISSIONS.VIEW_ALL_TASKS, "View All Tasks", "Allows viewing broader task queues within the authorized manager/admin scope."],
  [PERMISSIONS.CREATE_TASK, "Create Task", "Allows creating new tasks."],
  [PERMISSIONS.EDIT_TASK, "Edit Task", "Allows updating task execution and details."],
  [PERMISSIONS.DELETE_TASK, "Delete Task", "Allows deleting tasks."],
  [PERMISSIONS.UPLOAD_PROOFS, "Upload Proofs", "Allows uploading task proof attachments."],
  [PERMISSIONS.UPLOAD_LEGACY_DESIGN_DATA, "Upload Legacy Design Data (Deprecated)", "Deprecated historical permission. Legacy fixture upload is retired; grant Upload Native Design Data instead."],
  [PERMISSIONS.UPLOAD_NATIVE_DESIGN_DATA, "Upload Native Design Data", "Allows Design fixture ingestion via native spreadsheet session pipeline."],
  [PERMISSIONS.MANAGE_USERS, "Manage Users", "Allows managing user accounts."],
  [PERMISSIONS.CREATE_USER, "Create User", "Allows creating user accounts."],
  [PERMISSIONS.EDIT_USER, "Edit User", "Allows editing user account details."],
  [PERMISSIONS.ACTIVATE_USER, "Activate User", "Allows activating or deactivating user accounts."],
  [PERMISSIONS.MANAGE_ROLES, "Manage Roles", "Allows managing roles and permissions."],
  [PERMISSIONS.MANAGE_WORKFLOWS, "Manage Workflows", "Allows managing workflow configuration."],
  [PERMISSIONS.MANAGE_DEPARTMENTS, "Manage Departments", "Allows managing departments."],
  [PERMISSIONS.MANAGE_SHIFTS, "Manage Shifts", "Allows managing shifts."],
  [PERMISSIONS.MANAGE_MACHINES, "Manage Machines", "Allows managing machines."],
  [PERMISSIONS.MANAGE_KPIS, "Manage KPIs", "Allows managing KPI definitions."],
  [PERMISSIONS.MANAGE_ESCALATION_RULES, "Manage Escalation Rules", "Allows managing escalation rules."],
  [PERMISSIONS.VIEW_REPORTS, "View Reports", "Allows viewing reports."],
  [PERMISSIONS.EXPORT_REPORTS, "Export Reports", "Allows exporting reports."],
  [PERMISSIONS.VIEW_SELF_ANALYTICS, "View Self Analytics", "Allows viewing own personal KPIs."],
  [PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS, "View Department Analytics", "Allows viewing department metrics and top 5 users."],
  [PERMISSIONS.VIEW_ALL_DEPARTMENTS_ANALYTICS, "View All Departments", "Allows cross-department comparison."],
  [PERMISSIONS.VIEW_ALL_USERS_ANALYTICS, "View All Users", "Allows full user performance comparison."],
  [PERMISSIONS.VIEW_REWORK_ANALYTICS, "View Rework Analytics", "Allows access to rework intelligence."],
  [PERMISSIONS.VIEW_DEADLINE_ANALYTICS, "View Deadline Analytics", "Allows access to deadline reliability metrics."],
  [PERMISSIONS.VIEW_EFFICIENCY_ANALYTICS, "View Efficiency Analytics", "Allows access to stage efficiency analysis."],
  [PERMISSIONS.VIEW_WORKFLOW_HEALTH_ANALYTICS, "View Workflow Health", "Allows access to system-level health scores."],
  [PERMISSIONS.VIEW_PREDICTIVE_ANALYTICS, "View Predictive Insights", "Allows access to predictive delay and risk analysis."],
];

const DEPRECATED_PERMISSION_IDS = [
  PERMISSIONS.UPLOAD_LEGACY_DESIGN_DATA,
];

const DEFAULT_GRANTED_PERMISSION_IDS = Object.values(PERMISSIONS)
  .filter((permissionId) => permissionId !== PERMISSIONS.SELF_APPROVE)
  .filter((permissionId) => !DEPRECATED_PERMISSION_IDS.includes(permissionId));

const ROLE_DEFAULT_PERMISSIONS = {
  r1: DEFAULT_GRANTED_PERMISSION_IDS,
  r2: [
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.TRANSFER_TASK,
    PERMISSIONS.APPROVE_COMPLETED_TASK,
    PERMISSIONS.APPROVE_QUALITY,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.REOPEN_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.ACTIVATE_USER,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_WORKFLOWS,
    PERMISSIONS.MANAGE_DEPARTMENTS,
    PERMISSIONS.MANAGE_SHIFTS,
    PERMISSIONS.MANAGE_MACHINES,
    PERMISSIONS.MANAGE_KPIS,
    PERMISSIONS.MANAGE_ESCALATION_RULES,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    PERMISSIONS.VIEW_ALL_DEPARTMENTS_ANALYTICS,
    PERMISSIONS.VIEW_ALL_USERS_ANALYTICS,
    PERMISSIONS.VIEW_REWORK_ANALYTICS,
    PERMISSIONS.VIEW_DEADLINE_ANALYTICS,
    PERMISSIONS.VIEW_EFFICIENCY_ANALYTICS,
    PERMISSIONS.VIEW_WORKFLOW_HEALTH_ANALYTICS,
    PERMISSIONS.VIEW_PREDICTIVE_ANALYTICS,
  ],
  r3: [
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.TRANSFER_TASK,
    PERMISSIONS.APPROVE_COMPLETED_TASK,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.REOPEN_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    PERMISSIONS.VIEW_REWORK_ANALYTICS,
    PERMISSIONS.VIEW_DEADLINE_ANALYTICS,
    PERMISSIONS.VIEW_EFFICIENCY_ANALYTICS,
  ],
  r4: [
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.TRANSFER_TASK,
    PERMISSIONS.APPROVE_COMPLETED_TASK,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.REOPEN_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
  ],
  r5: [
    PERMISSIONS.APPROVE_QUALITY,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    PERMISSIONS.VIEW_REWORK_ANALYTICS,
    PERMISSIONS.VIEW_DEADLINE_ANALYTICS,
  ],
  r6: [
    PERMISSIONS.VIEW_SELF_TASKS,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
  ],
  r7: [
    PERMISSIONS.VIEW_SELF_TASKS,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
  ],
};

const TASK_STATUSES = {
  CREATED: "created",
  ASSIGNED: "assigned",
  IN_PROGRESS: "in_progress",
  ON_HOLD: "on_hold",
  UNDER_REVIEW: "under_review",
  REWORK: "rework",
  CLOSED: "closed",
  CANCELLED: "cancelled",
};

const VERIFICATION_STATUSES = {
  PENDING: "pending",
  MANAGER_APPROVED: "manager_approved",
  QUALITY_PENDING: "quality_pending",
  APPROVED: "approved",
  REJECTED: "rejected",
};

const TASK_TYPES = {
  DEPARTMENT_WORKFLOW: "department_workflow",
  CUSTOM: "custom",
  ADDITIONAL_DESIGN: "additional_design",
};

const TASK_SOURCES = {
  ADMIN_MANUAL: "admin_manual",
  WORKFLOW_AUTO: "workflow_auto",
  SYSTEM_GENERATED: "system_generated",
  EXCEL_IMPORT: "excel_import",
};

const PROJECT_STATUSES = {
  ACTIVE: "active",
  ON_HOLD: "on_hold",
  COMPLETED: "completed",
  RELEASED: "released",
};

const TASK_TRANSITIONS = {
  [TASK_STATUSES.CREATED]: [TASK_STATUSES.ASSIGNED],
  [TASK_STATUSES.ASSIGNED]: [TASK_STATUSES.IN_PROGRESS],
  [TASK_STATUSES.IN_PROGRESS]: [TASK_STATUSES.UNDER_REVIEW, TASK_STATUSES.ON_HOLD],
  [TASK_STATUSES.ON_HOLD]: [TASK_STATUSES.IN_PROGRESS],
  [TASK_STATUSES.UNDER_REVIEW]: [TASK_STATUSES.REWORK, TASK_STATUSES.CLOSED],
  [TASK_STATUSES.REWORK]: [TASK_STATUSES.IN_PROGRESS],
  [TASK_STATUSES.CLOSED]: [],
  [TASK_STATUSES.CANCELLED]: [],
};

module.exports = {
  DEPRECATED_PERMISSION_IDS,
  PERMISSION_DEFINITIONS,
  PERMISSIONS,
  PROJECT_STATUSES,
  ROLE_LEVELS,
  ROLE_DEFAULT_PERMISSIONS,
  TASK_SOURCES,
  TASK_STATUSES,
  TASK_TYPES,
  TASK_TRANSITIONS,
  USER_SCOPES,
  VERIFICATION_STATUSES,
};
