const ROLE_LEVELS = {
  r1: 1,
  r2: 2,
  r3: 3,
  r4: 4,
  r5: 4,
  r6: 5,
  r7: 6,
};

const USER_SCOPES = {
  ACCESSIBLE: "accessible",
  ASSIGNABLE: "assignable",
};

const PERMISSIONS = {
  ASSIGN_TASK: "can_assign_tasks",
  TRANSFER_TASK: "transfer_task",
  APPROVE_COMPLETED_TASK: "approve_completed_task",
  SELF_APPROVE: "self_approve",
  APPROVE_QUALITY: "can_approve_quality",
  CHANGE_FIXTURE_STAGE: "change_fixture_stage",
  DELETE_WBS_BATCH: "delete_wbs_batch",
  REOPEN_FIXTURE_STAGE: "reopen_fixture_stage",
  MANIPULATE_FIXTURE_STAGE: "manipulate_fixture_stage",
  VIEW_SELF_TASKS: "can_view_self_tasks",
  VIEW_ALL_TASKS: "can_view_all_tasks",
  CREATE_TASK: "can_create_task",
  EDIT_TASK: "can_edit_task",
  DELETE_TASK: "can_delete_task",
  UPLOAD_PROOFS: "can_upload_proofs",
  UPLOAD_LEGACY_DESIGN_DATA: "upload_legacy_design_data",
  UPLOAD_NATIVE_DESIGN_DATA: "upload_native_design_data",
  MANAGE_USERS: "can_manage_users",
  CREATE_USER: "can_create_user",
  EDIT_USER: "can_edit_user",
  ACTIVATE_USER: "can_activate_user",
  MANAGE_ROLES: "can_manage_roles",
  MANAGE_WORKFLOWS: "can_manage_workflows",
  MANAGE_DEPARTMENTS: "can_manage_departments",
  MANAGE_SHIFTS: "can_manage_shifts",
  MANAGE_MACHINES: "can_manage_machines",
  MANAGE_KPIS: "can_manage_kpis",
  MANAGE_ESCALATION_RULES: "can_manage_escalation_rules",
  VIEW_REPORTS: "can_view_reports",
  EXPORT_REPORTS: "can_export_reports",
  RECEIVE_EXECUTIVE_DESKTOP_NOTIFICATIONS: "receive_executive_desktop_notifications",
  VIEW_PROJECT_SCOPE: "view_project_scope",
  EDIT_PROJECT_PLANNED_TIME: "edit_project_planned_time",
  VIEW_TEAM_ACTIVITY: "view_team_activity",
  
  // New Strict Analytics Permissions
  VIEW_SELF_ANALYTICS: "view_self_analytics",
  VIEW_DEPARTMENT_ANALYTICS: "view_department_analytics",
  VIEW_ALL_DEPARTMENTS_ANALYTICS: "view_all_departments_analytics",
  VIEW_ALL_USERS_ANALYTICS: "view_all_users_analytics",
  
  VIEW_REWORK_ANALYTICS: "view_rework_analytics",
  VIEW_DEADLINE_ANALYTICS: "view_deadline_analytics",
  VIEW_EFFICIENCY_ANALYTICS: "view_efficiency_analytics",
  VIEW_WORKFLOW_HEALTH_ANALYTICS: "view_workflow_health",
  VIEW_PREDICTIVE_ANALYTICS: "view_predictive_analytics",
  CONTROL_DESIGN_WORKSPACE_VIEW: "control_design.workspace.view",
  CONTROL_DESIGN_PROJECTS_VIEW_ASSIGNED: "control_design.projects.view_assigned",
  CONTROL_DESIGN_PROJECTS_VIEW_ALL: "control_design.projects.view_all",
  CONTROL_DESIGN_PROJECTS_CREATE: "control_design.projects.create",
  CONTROL_DESIGN_PROJECTS_EDIT: "control_design.projects.edit",
  CONTROL_DESIGN_PROJECTS_ASSIGN: "control_design.projects.assign",
  CONTROL_DESIGN_PROJECTS_REASSIGN: "control_design.projects.reassign",
  CONTROL_DESIGN_PROJECTS_CANCEL: "control_design.projects.cancel",
  CONTROL_DESIGN_STAGES_START: "control_design.stages.start",
  CONTROL_DESIGN_STAGES_SUBMIT: "control_design.stages.submit",
  CONTROL_DESIGN_PATHS_UPDATE: "control_design.paths.update",
  CONTROL_DESIGN_APPROVALS_REVIEW: "control_design.approvals.review",
  CONTROL_DESIGN_APPROVALS_APPROVE: "control_design.approvals.approve",
  CONTROL_DESIGN_APPROVALS_REQUEST_CHANGES: "control_design.approvals.request_changes",
  CONTROL_DESIGN_PROOFS_VIEW: "control_design.proofs.view",
  CONTROL_DESIGN_PROOFS_UPLOAD: "control_design.proofs.upload",
  CONTROL_DESIGN_REVISIONS_RAISE: "control_design.revisions.raise",
  CONTROL_DESIGN_REVISIONS_EXECUTE: "control_design.revisions.execute",
  CONTROL_DESIGN_REVISIONS_REVIEW: "control_design.revisions.review",
  CONTROL_DESIGN_STAGES_MARK_PRE_COMPLETED: "control_design.stages.mark_pre_completed",
  CONTROL_DESIGN_STAGES_OVERRIDE_UNLOCK: "control_design.stages.override_unlock",
  CONTROL_DESIGN_STAGES_SKIP_OVERRIDE: "control_design.stages.skip_override",
  CONTROL_DESIGN_PROJECTS_MARK_DISPATCHED: "control_design.projects.mark_dispatched",
  CONTROL_DESIGN_PROJECTS_REOPEN_AFTER_DISPATCH: "control_design.projects.reopen_after_dispatch",
  CONTROL_DESIGN_AUDIT_VIEW: "control_design.audit.view",
  CONTROL_DESIGN_REPORTS_VIEW: "control_design.reports.view",
};

PERMISSIONS.CONTROL_DESIGN_CREATE_PROJECTS = PERMISSIONS.CONTROL_DESIGN_PROJECTS_CREATE;
PERMISSIONS.CONTROL_DESIGN_VIEW_ALL_PROJECTS = PERMISSIONS.CONTROL_DESIGN_PROJECTS_VIEW_ALL;
PERMISSIONS.CONTROL_DESIGN_ASSIGN_PROJECTS = PERMISSIONS.CONTROL_DESIGN_PROJECTS_ASSIGN;
PERMISSIONS.CONTROL_DESIGN_REASSIGN_PROJECTS = PERMISSIONS.CONTROL_DESIGN_PROJECTS_REASSIGN;

const CONTROL_DESIGN_MEMBER_PERMISSION_IDS = [
  PERMISSIONS.CONTROL_DESIGN_WORKSPACE_VIEW,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_VIEW_ASSIGNED,
  PERMISSIONS.CONTROL_DESIGN_STAGES_START,
  PERMISSIONS.CONTROL_DESIGN_STAGES_SUBMIT,
  PERMISSIONS.CONTROL_DESIGN_PATHS_UPDATE,
  PERMISSIONS.CONTROL_DESIGN_PROOFS_VIEW,
  PERMISSIONS.CONTROL_DESIGN_PROOFS_UPLOAD,
  PERMISSIONS.CONTROL_DESIGN_REVISIONS_EXECUTE,
];

const CONTROL_DESIGN_APPROVER_PERMISSION_IDS = [
  PERMISSIONS.CONTROL_DESIGN_WORKSPACE_VIEW,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_VIEW_ALL,
  PERMISSIONS.CONTROL_DESIGN_APPROVALS_REVIEW,
  PERMISSIONS.CONTROL_DESIGN_APPROVALS_APPROVE,
  PERMISSIONS.CONTROL_DESIGN_APPROVALS_REQUEST_CHANGES,
  PERMISSIONS.CONTROL_DESIGN_PROOFS_VIEW,
  PERMISSIONS.CONTROL_DESIGN_REVISIONS_REVIEW,
  PERMISSIONS.CONTROL_DESIGN_AUDIT_VIEW,
  PERMISSIONS.CONTROL_DESIGN_REPORTS_VIEW,
];

const CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS = [
  ...CONTROL_DESIGN_MEMBER_PERMISSION_IDS,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_VIEW_ALL,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_CREATE,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_EDIT,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_ASSIGN,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_REASSIGN,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_CANCEL,
  PERMISSIONS.CONTROL_DESIGN_APPROVALS_REVIEW,
  PERMISSIONS.CONTROL_DESIGN_APPROVALS_APPROVE,
  PERMISSIONS.CONTROL_DESIGN_APPROVALS_REQUEST_CHANGES,
  PERMISSIONS.CONTROL_DESIGN_REVISIONS_RAISE,
  PERMISSIONS.CONTROL_DESIGN_REVISIONS_REVIEW,
  PERMISSIONS.CONTROL_DESIGN_STAGES_MARK_PRE_COMPLETED,
  PERMISSIONS.CONTROL_DESIGN_STAGES_OVERRIDE_UNLOCK,
  PERMISSIONS.CONTROL_DESIGN_STAGES_SKIP_OVERRIDE,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_MARK_DISPATCHED,
  PERMISSIONS.CONTROL_DESIGN_PROJECTS_REOPEN_AFTER_DISPATCH,
  PERMISSIONS.CONTROL_DESIGN_AUDIT_VIEW,
  PERMISSIONS.CONTROL_DESIGN_REPORTS_VIEW,
];

const CONTROL_DESIGN_ROLE_PERMISSION_BUNDLES = {
  r1: CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  r2: CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  r3: CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  r4: CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  r5: CONTROL_DESIGN_APPROVER_PERMISSION_IDS,
  r6: CONTROL_DESIGN_MEMBER_PERMISSION_IDS,
  r7: CONTROL_DESIGN_MEMBER_PERMISSION_IDS,
};

const PERMISSION_DEFINITIONS = [
  [PERMISSIONS.ASSIGN_TASK, "Assign Task", "Allows assigning tasks to other users."],
  [PERMISSIONS.TRANSFER_TASK, "Transfer Task", "Allows transferring Design stage work while preserving contribution history."],
  [PERMISSIONS.APPROVE_COMPLETED_TASK, "Approve Completed Task", "Allows approving completed non-quality task submissions."],
  [PERMISSIONS.SELF_APPROVE, "Self Approve", "Allows a user to approve their own task when they already have the relevant approval permission."],
  [PERMISSIONS.APPROVE_QUALITY, "Approve Quality", "Allows performing quality-stage approval."],
  [PERMISSIONS.CHANGE_FIXTURE_STAGE, "Change Fixture Stage", "Allows controlled fixture stage transitions."],
  [PERMISSIONS.DELETE_WBS_BATCH, "Delete WBS Batch", "Allows deleting owned WBS upload batches subject to ownership controls."],
  [PERMISSIONS.REOPEN_FIXTURE_STAGE, "Reopen Fixture Stage", "Allows reopening a completed fixture stage with revision history."],
  [PERMISSIONS.MANIPULATE_FIXTURE_STAGE, "Manipulate Fixture Stage", "Allows legacy-only manual fixture stage correction."],
  [PERMISSIONS.VIEW_SELF_TASKS, "View Self Tasks Only", "Allows viewing only tasks assigned to self or created by self."],
  [PERMISSIONS.VIEW_ALL_TASKS, "View All Tasks", "Allows viewing broader task queues within the authorized manager/admin scope."],
  [PERMISSIONS.CREATE_TASK, "Create Task", "Allows creating new tasks."],
  [PERMISSIONS.EDIT_TASK, "Edit Task", "Allows updating task execution and details."],
  [PERMISSIONS.DELETE_TASK, "Delete Task", "Allows deleting tasks."],
  [PERMISSIONS.UPLOAD_PROOFS, "Upload Proofs", "Allows uploading task proof attachments."],
  [PERMISSIONS.UPLOAD_LEGACY_DESIGN_DATA, "Upload Legacy Design Data (Deprecated)", "Deprecated historical permission. Legacy fixture upload is retired; grant Upload Native Design Data instead."],
  [PERMISSIONS.UPLOAD_NATIVE_DESIGN_DATA, "Upload Native Design Data", "Allows Design fixture ingestion via native spreadsheet session pipeline."],
  [PERMISSIONS.MANAGE_USERS, "Manage Users", "Allows managing user accounts."],
  [PERMISSIONS.CREATE_USER, "Create User", "Allows creating user accounts."],
  [PERMISSIONS.EDIT_USER, "Edit User", "Allows editing user account details."],
  [PERMISSIONS.ACTIVATE_USER, "Activate User", "Allows activating or deactivating user accounts."],
  [PERMISSIONS.MANAGE_ROLES, "Manage Roles", "Allows managing roles and permissions."],
  [PERMISSIONS.MANAGE_WORKFLOWS, "Manage Workflows", "Allows managing workflow configuration."],
  [PERMISSIONS.MANAGE_DEPARTMENTS, "Manage Departments", "Allows managing departments."],
  [PERMISSIONS.MANAGE_SHIFTS, "Manage Shifts", "Allows managing shifts."],
  [PERMISSIONS.MANAGE_MACHINES, "Manage Machines", "Allows managing machines."],
  [PERMISSIONS.MANAGE_KPIS, "Manage KPIs", "Allows managing KPI definitions."],
  [PERMISSIONS.MANAGE_ESCALATION_RULES, "Manage Escalation Rules", "Allows managing escalation rules."],
  [PERMISSIONS.VIEW_REPORTS, "View Reports", "Allows viewing reports."],
  [PERMISSIONS.EXPORT_REPORTS, "Export Reports", "Allows exporting reports."],
  [PERMISSIONS.RECEIVE_EXECUTIVE_DESKTOP_NOTIFICATIONS, "Receive Executive Desktop Notifications", "Allows receiving executive desktop notifications for project release events."],
  [PERMISSIONS.VIEW_PROJECT_SCOPE, "View Project Scope", "Allows Admin, CEO, and Director roles to view active project scope and planned hours."],
  [PERMISSIONS.EDIT_PROJECT_PLANNED_TIME, "Edit Project Planned Time", "Allows assigned Design leaders and co-leaders to edit authorized project planning stages."],
  [PERMISSIONS.VIEW_TEAM_ACTIVITY, "View Team Activity", "Allows leaders and co-leaders to view activity for employees in their mapped team."],
  [PERMISSIONS.VIEW_SELF_ANALYTICS, "View Self Analytics", "Allows viewing own personal KPIs."],
  [PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS, "View Department Analytics", "Allows viewing department metrics and top 5 users."],
  [PERMISSIONS.VIEW_ALL_DEPARTMENTS_ANALYTICS, "View All Departments", "Allows cross-department comparison."],
  [PERMISSIONS.VIEW_ALL_USERS_ANALYTICS, "View All Users", "Allows full user performance comparison."],
  [PERMISSIONS.VIEW_REWORK_ANALYTICS, "View Rework Analytics", "Allows access to rework intelligence."],
  [PERMISSIONS.VIEW_DEADLINE_ANALYTICS, "View Deadline Analytics", "Allows access to deadline reliability metrics."],
  [PERMISSIONS.VIEW_EFFICIENCY_ANALYTICS, "View Efficiency Analytics", "Allows access to stage efficiency analysis."],
  [PERMISSIONS.VIEW_WORKFLOW_HEALTH_ANALYTICS, "View Workflow Health", "Allows access to system-level health scores."],
  [PERMISSIONS.VIEW_PREDICTIVE_ANALYTICS, "View Predictive Insights", "Allows access to predictive delay and risk analysis."],
  [PERMISSIONS.CONTROL_DESIGN_WORKSPACE_VIEW, "View Control Design Workspace", "Allows entering the Control Design workspace within the Control Design subdivision."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_VIEW_ASSIGNED, "View Assigned Control Design Projects", "Allows viewing Control Design projects assigned to the current user."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_VIEW_ALL, "View All Control Design Projects", "Allows viewing all Control Design project workflows in scope."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_CREATE, "Create Control Design Projects", "Allows creating Control Design project workflows."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_EDIT, "Edit Control Design Projects", "Allows editing Control Design project metadata."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_ASSIGN, "Assign Control Design Projects", "Allows assigning Control Design project ownership."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_REASSIGN, "Reassign Control Design Projects", "Allows reassigning Control Design project ownership."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_CANCEL, "Cancel Control Design Projects", "Allows cancelling Control Design projects."],
  [PERMISSIONS.CONTROL_DESIGN_STAGES_START, "Start Control Design Stages", "Allows an assigned owner to start unlocked Control Design stages."],
  [PERMISSIONS.CONTROL_DESIGN_STAGES_SUBMIT, "Submit Control Design Stages", "Allows an assigned owner to submit Control Design stages."],
  [PERMISSIONS.CONTROL_DESIGN_PATHS_UPDATE, "Update Control Design Paths", "Allows updating Control Design stage document paths."],
  [PERMISSIONS.CONTROL_DESIGN_APPROVALS_REVIEW, "Review Control Design Approvals", "Allows viewing Control Design approval queues."],
  [PERMISSIONS.CONTROL_DESIGN_APPROVALS_APPROVE, "Approve Control Design Submissions", "Allows approving pending Control Design submissions."],
  [PERMISSIONS.CONTROL_DESIGN_APPROVALS_REQUEST_CHANGES, "Request Control Design Changes", "Allows requesting changes on pending Control Design submissions."],
  [PERMISSIONS.CONTROL_DESIGN_PROOFS_VIEW, "View Control Design Proofs", "Allows opening and downloading Control Design work proof files."],
  [PERMISSIONS.CONTROL_DESIGN_PROOFS_UPLOAD, "Upload Control Design Proofs", "Allows assigned owners to upload and remove unsubmitted Control Design work proof files."],
  [PERMISSIONS.CONTROL_DESIGN_REVISIONS_RAISE, "Raise Control Design Revisions", "Allows raising post-approval Control Design revisions."],
  [PERMISSIONS.CONTROL_DESIGN_REVISIONS_EXECUTE, "Execute Control Design Revisions", "Allows assigned owners to execute Control Design revisions."],
  [PERMISSIONS.CONTROL_DESIGN_REVISIONS_REVIEW, "Review Control Design Revisions", "Allows reviewing submitted Control Design revisions."],
  [PERMISSIONS.CONTROL_DESIGN_STAGES_MARK_PRE_COMPLETED, "Mark Control Design Stages Pre-Completed", "Allows marking Control Design stages pre-completed with evidence."],
  [PERMISSIONS.CONTROL_DESIGN_STAGES_OVERRIDE_UNLOCK, "Override Unlock Control Design Stages", "Allows override-unlocking Control Design stages."],
  [PERMISSIONS.CONTROL_DESIGN_STAGES_SKIP_OVERRIDE, "Skip Control Design Stages By Override", "Allows recording Control Design stages skipped by override."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_MARK_DISPATCHED, "Mark Control Design Projects Dispatched", "Allows marking ready Control Design projects as dispatched."],
  [PERMISSIONS.CONTROL_DESIGN_PROJECTS_REOPEN_AFTER_DISPATCH, "Reopen Control Design Projects After Dispatch", "Allows reopening dispatched Control Design projects."],
  [PERMISSIONS.CONTROL_DESIGN_AUDIT_VIEW, "View Control Design Audit", "Allows viewing Control Design audit history."],
  [PERMISSIONS.CONTROL_DESIGN_REPORTS_VIEW, "View Control Design Reports", "Allows viewing Control Design reports."],
];

const DEPRECATED_PERMISSION_IDS = [
  PERMISSIONS.UPLOAD_LEGACY_DESIGN_DATA,
];

const DEFAULT_GRANTED_PERMISSION_IDS = [...new Set(Object.values(PERMISSIONS))]
  .filter((permissionId) => permissionId !== PERMISSIONS.SELF_APPROVE)
  .filter((permissionId) => !DEPRECATED_PERMISSION_IDS.includes(permissionId));

const ROLE_DEFAULT_PERMISSIONS = {
  r1: DEFAULT_GRANTED_PERMISSION_IDS,
  r2: [
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.TRANSFER_TASK,
    PERMISSIONS.APPROVE_COMPLETED_TASK,
    PERMISSIONS.APPROVE_QUALITY,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.REOPEN_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.ACTIVATE_USER,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_WORKFLOWS,
    PERMISSIONS.MANAGE_DEPARTMENTS,
    PERMISSIONS.MANAGE_SHIFTS,
    PERMISSIONS.MANAGE_MACHINES,
    PERMISSIONS.MANAGE_KPIS,
    PERMISSIONS.MANAGE_ESCALATION_RULES,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    PERMISSIONS.VIEW_ALL_DEPARTMENTS_ANALYTICS,
    PERMISSIONS.VIEW_ALL_USERS_ANALYTICS,
    PERMISSIONS.VIEW_REWORK_ANALYTICS,
    PERMISSIONS.VIEW_DEADLINE_ANALYTICS,
    PERMISSIONS.VIEW_EFFICIENCY_ANALYTICS,
    PERMISSIONS.VIEW_WORKFLOW_HEALTH_ANALYTICS,
    PERMISSIONS.VIEW_PREDICTIVE_ANALYTICS,
    ...CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  ],
  r3: [
    PERMISSIONS.VIEW_TEAM_ACTIVITY,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.TRANSFER_TASK,
    PERMISSIONS.APPROVE_COMPLETED_TASK,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.REOPEN_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    PERMISSIONS.VIEW_REWORK_ANALYTICS,
    PERMISSIONS.VIEW_DEADLINE_ANALYTICS,
    PERMISSIONS.VIEW_EFFICIENCY_ANALYTICS,
    ...CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  ],
  r4: [
    PERMISSIONS.VIEW_TEAM_ACTIVITY,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.TRANSFER_TASK,
    PERMISSIONS.APPROVE_COMPLETED_TASK,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.REOPEN_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    ...CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  ],
  r5: [
    PERMISSIONS.APPROVE_QUALITY,
    PERMISSIONS.CHANGE_FIXTURE_STAGE,
    PERMISSIONS.VIEW_ALL_TASKS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    PERMISSIONS.VIEW_REWORK_ANALYTICS,
    PERMISSIONS.VIEW_DEADLINE_ANALYTICS,
    ...CONTROL_DESIGN_APPROVER_PERMISSION_IDS,
  ],
  r6: [
    PERMISSIONS.VIEW_SELF_TASKS,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    ...CONTROL_DESIGN_MEMBER_PERMISSION_IDS,
  ],
  r7: [
    PERMISSIONS.VIEW_SELF_TASKS,
    PERMISSIONS.EDIT_TASK,
    PERMISSIONS.UPLOAD_PROOFS,
    PERMISSIONS.VIEW_SELF_ANALYTICS,
    ...CONTROL_DESIGN_MEMBER_PERMISSION_IDS,
  ],
};

const TASK_STATUSES = {
  CREATED: "created",
  ASSIGNED: "assigned",
  IN_PROGRESS: "in_progress",
  ON_HOLD: "on_hold",
  UNDER_REVIEW: "under_review",
  REWORK: "rework",
  CLOSED: "closed",
  CANCELLED: "cancelled",
};

const VERIFICATION_STATUSES = {
  PENDING: "pending",
  MANAGER_APPROVED: "manager_approved",
  QUALITY_PENDING: "quality_pending",
  APPROVED: "approved",
  REJECTED: "rejected",
};

const TASK_TYPES = {
  DEPARTMENT_WORKFLOW: "department_workflow",
  CUSTOM: "custom",
  ADDITIONAL_DESIGN: "additional_design",
  DESIGN_2D_COMPLETION: "design_2d_completion",
};

const TASK_SOURCES = {
  ADMIN_MANUAL: "admin_manual",
  WORKFLOW_AUTO: "workflow_auto",
  SYSTEM_GENERATED: "system_generated",
  EXCEL_IMPORT: "excel_import",
  DESIGN_2D_COMPLETION: "design_2d_completion",
};

const PROJECT_STATUSES = {
  ACTIVE: "active",
  ON_HOLD: "on_hold",
  COMPLETED: "completed",
  RELEASED: "released",
};

const TASK_TRANSITIONS = {
  [TASK_STATUSES.CREATED]: [TASK_STATUSES.ASSIGNED],
  [TASK_STATUSES.ASSIGNED]: [TASK_STATUSES.IN_PROGRESS],
  [TASK_STATUSES.IN_PROGRESS]: [TASK_STATUSES.UNDER_REVIEW, TASK_STATUSES.ON_HOLD],
  [TASK_STATUSES.ON_HOLD]: [TASK_STATUSES.IN_PROGRESS],
  [TASK_STATUSES.UNDER_REVIEW]: [TASK_STATUSES.REWORK, TASK_STATUSES.CLOSED],
  [TASK_STATUSES.REWORK]: [TASK_STATUSES.IN_PROGRESS],
  [TASK_STATUSES.CLOSED]: [],
  [TASK_STATUSES.CANCELLED]: [],
};

module.exports = {
  DEPRECATED_PERMISSION_IDS,
  CONTROL_DESIGN_APPROVER_PERMISSION_IDS,
  CONTROL_DESIGN_LEADERSHIP_PERMISSION_IDS,
  CONTROL_DESIGN_MEMBER_PERMISSION_IDS,
  CONTROL_DESIGN_ROLE_PERMISSION_BUNDLES,
  PERMISSION_DEFINITIONS,
  PERMISSIONS,
  PROJECT_STATUSES,
  ROLE_LEVELS,
  ROLE_DEFAULT_PERMISSIONS,
  TASK_SOURCES,
  TASK_STATUSES,
  TASK_TYPES,
  TASK_TRANSITIONS,
  USER_SCOPES,
  VERIFICATION_STATUSES,
};
