const DAY = 24 * 60 * 60 * 1000;

const now = Date.now();
const futureIso = (days) => new Date(now + days * DAY).toISOString();
const pastIso = (days) => new Date(now - days * DAY).toISOString();

const roles = [
  { id: "r1", name: "Admin", hierarchy_level: 1, permissions: { all: true }, scope: "global", parent_role: null },
  {
    id: "r2",
    name: "Plant Head",
    hierarchy_level: 2,
    permissions: {
      can_assign_tasks: true,
      can_verify_task: true,
      can_approve_quality: true,
      can_view_all_tasks: true,
      can_create_task: true,
      can_edit_task: true,
      can_manage_users: true,
      can_create_user: true,
      can_edit_user: true,
      can_activate_user: true,
      can_manage_roles: true,
      can_manage_workflows: true,
      can_manage_departments: true,
      can_manage_shifts: true,
      can_manage_machines: true,
      can_manage_kpis: true,
      can_manage_escalation_rules: true,
      can_upload_proofs: true,
      can_view_reports: true,
      can_export_reports: true,
    },
    scope: "department",
    parent_role: "r1",
  },
  {
    id: "r3",
    name: "Line Manager",
    hierarchy_level: 3,
    permissions: {
      can_assign_tasks: true,
      can_verify_task: true,
      can_view_all_tasks: true,
      can_create_task: true,
      can_edit_task: true,
      can_upload_proofs: true,
      can_view_reports: true,
    },
    scope: "team",
    parent_role: "r2",
  },
  {
    id: "r4",
    name: "Shift Incharge",
    hierarchy_level: 4,
    permissions: {
      can_assign_tasks: true,
      can_verify_task: true,
      can_view_all_tasks: true,
      can_create_task: true,
      can_edit_task: true,
      can_upload_proofs: true,
    },
    scope: "team",
    parent_role: "r3",
  },
  {
    id: "r5",
    name: "Quality Inspector",
    hierarchy_level: 4,
    permissions: {
      can_verify_task: true,
      can_approve_quality: true,
      can_view_all_tasks: true,
      can_view_reports: true,
    },
    scope: "department",
    parent_role: "r3",
  },
  {
    id: "r6",
    name: "Maintenance Engineer",
    hierarchy_level: 5,
    permissions: {
      can_edit_task: true,
      can_upload_proofs: true,
    },
    scope: "self",
    parent_role: "r4",
  },
  {
    id: "r7",
    name: "Operator",
    hierarchy_level: 6,
    permissions: {
      can_edit_task: true,
      can_upload_proofs: true,
    },
    scope: "self",
    parent_role: "r4",
  },
];

const departments = [
  { id: "d1", name: "Production", parent_department: null },
  { id: "d2", name: "Quality Assurance", parent_department: null },
  { id: "d3", name: "Maintenance", parent_department: null },
];

const tasks = [
  {
    title: "Lubrication schedule - Week 15",
    description: "Execute weekly lubrication on all listed production machinery.",
    assigned_to: "EMP009",
    assigned_by: "EMP005",
    department_id: "d1",
    status: "in_progress",
    verification_status: "pending",
    priority: "medium",
    deadline: futureIso(1),
    created_at: pastIso(2),
    started_at: pastIso(1),
    completed_at: null,
    verified_at: null,
    proof_url: null,
    proof_type: null,
    remarks: null,
  },
  {
    title: "Batch 2847 quality check",
    description: "Perform dimensional and visual inspection for batch 2847.",
    assigned_to: "EMP007",
    assigned_by: "EMP004",
    department_id: "d2",
    status: "completed",
    verification_status: "pending",
    priority: "high",
    deadline: futureIso(0),
    created_at: pastIso(3),
    started_at: pastIso(2),
    completed_at: pastIso(1),
    verified_at: null,
    proof_url: "/proof/batch-2847-report.pdf",
    proof_type: "pdf",
    remarks: null,
  },
  {
    title: "Replace conveyor belt motor",
    description: "Motor #CB-12 is showing vibration anomalies. Replace with a compatible unit.",
    assigned_to: "EMP008",
    assigned_by: "EMP001",
    department_id: "d3",
    status: "completed",
    verification_status: "approved",
    priority: "critical",
    deadline: pastIso(1),
    created_at: pastIso(6),
    started_at: pastIso(5),
    completed_at: pastIso(2),
    verified_at: pastIso(1),
    proof_url: "/proof/motor-replacement.jpg",
    proof_type: "image",
    remarks: "Verified by admin after installation check.",
  },
  {
    title: "Line 2 workstation cleanup",
    description: "Restore standard 5S condition for workstations 2A through 2D.",
    assigned_to: "EMP010",
    assigned_by: "EMP006",
    department_id: "d2",
    status: "not_started",
    verification_status: "pending",
    priority: "low",
    deadline: futureIso(3),
    created_at: pastIso(1),
    started_at: null,
    completed_at: null,
    verified_at: null,
    proof_url: null,
    proof_type: null,
    remarks: null,
  },
  {
    title: "Safety audit - extinguishers",
    description: "Inspect all fire extinguishers in production and log tag expiry.",
    assigned_to: "EMP009",
    assigned_by: "EMP003",
    department_id: "d1",
    status: "completed",
    verification_status: "rejected",
    priority: "high",
    deadline: pastIso(2),
    created_at: pastIso(5),
    started_at: pastIso(4),
    completed_at: pastIso(3),
    verified_at: null,
    proof_url: "/proof/extinguisher-audit.jpg",
    proof_type: "image",
    remarks: "Photos missing for extinguisher station P-07.",
  },
  {
    title: "Electrical panel inspection",
    description: "Carry out a thermal inspection on the main distribution panels.",
    assigned_to: "EMP008",
    assigned_by: "EMP001",
    department_id: "d3",
    status: "on_hold",
    verification_status: "pending",
    priority: "medium",
    deadline: futureIso(4),
    created_at: pastIso(2),
    started_at: pastIso(1),
    completed_at: null,
    verified_at: null,
    proof_url: null,
    proof_type: null,
    remarks: "Waiting for maintenance shutdown window approval.",
  },
];

module.exports = {
  departments,
  roles,
  tasks,
};
