INSERT INTO permissions (id, name, description)
VALUES
  ('can_assign_tasks', 'Assign Task', 'Allows assigning tasks to other users.'),
  ('transfer_task', 'Transfer Task', 'Allows transferring Design stage work while preserving contribution history.'),
  ('approve_completed_task', 'Approve Completed Task', 'Allows approving completed non-quality task submissions.'),
  ('can_approve_quality', 'Approve Quality', 'Allows performing quality-stage approval.'),
  ('can_view_self_tasks', 'View Self Tasks Only', 'Allows viewing only tasks assigned to self or created by self.'),
  ('can_view_all_tasks', 'View All Tasks', 'Allows viewing broader task queues within the authorized manager/admin scope.'),
  ('can_create_task', 'Create Task', 'Allows creating new tasks.'),
  ('can_edit_task', 'Edit Task', 'Allows updating task execution and details.'),
  ('can_delete_task', 'Delete Task', 'Allows deleting tasks.'),
  ('can_upload_proofs', 'Upload Proofs', 'Allows uploading task proof attachments.'),
  ('upload_legacy_design_data', 'Upload Legacy Design Data', 'Allows Design fixture ingestion via legacy Excel/paste pipeline (temporary during native rollout).'),
  ('upload_native_design_data', 'Upload Native Design Data', 'Allows Design fixture ingestion via native spreadsheet session pipeline.'),
  ('can_manage_users', 'Manage Users', 'Allows managing user accounts.'),
  ('can_create_user', 'Create User', 'Allows creating user accounts.'),
  ('can_edit_user', 'Edit User', 'Allows editing user account details.'),
  ('can_activate_user', 'Activate User', 'Allows activating or deactivating user accounts.'),
  ('can_manage_roles', 'Manage Roles', 'Allows managing roles and permissions.'),
  ('can_manage_workflows', 'Manage Workflows', 'Allows managing workflow configuration.'),
  ('can_manage_departments', 'Manage Departments', 'Allows managing departments.'),
  ('can_manage_shifts', 'Manage Shifts', 'Allows managing shifts.'),
  ('can_manage_machines', 'Manage Machines', 'Allows managing machines.'),
  ('can_manage_task_templates', 'Manage Task Templates', 'Allows managing task templates.'),
  ('can_manage_kpis', 'Manage KPIs', 'Allows managing KPI definitions.'),
  ('can_manage_escalation_rules', 'Manage Escalation Rules', 'Allows managing escalation rules.'),
  ('can_view_reports', 'View Reports', 'Allows viewing reports.'),
  ('can_export_reports', 'Export Reports', 'Allows exporting reports.')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    updated_at = NOW();
