INSERT INTO permissions (id, name, description)
VALUES
  ('can_assign_tasks', 'Assign Task', 'Allows assigning tasks to other users.'),
  ('transfer_task', 'Transfer Task', 'Allows transferring Design stage work while preserving contribution history.'),
  ('approve_completed_task', 'Approve Completed Task', 'Allows approving completed non-quality task submissions.'),
  ('can_approve_quality', 'Approve Quality', 'Allows performing quality-stage approval.'),
  ('can_view_self_tasks', 'View Self Tasks Only', 'Allows viewing only tasks assigned to self or created by self.'),
  ('can_view_all_tasks', 'View All Tasks', 'Allows viewing broader task queues within the authorized manager/admin scope.'),
  ('can_create_task', 'Create Task', 'Allows creating new tasks.'),
  ('can_edit_task', 'Edit Task', 'Allows updating task execution and details.'),
  ('can_delete_task', 'Delete Task', 'Allows deleting tasks.'),
  ('can_upload_proofs', 'Upload Proofs', 'Allows uploading task proof attachments.'),
  ('upload_legacy_design_data', 'Upload Legacy Design Data (Deprecated)', 'Deprecated historical permission. Legacy fixture upload is retired; grant Upload Native Design Data instead.'),
  ('upload_native_design_data', 'Upload Native Design Data', 'Allows Design fixture ingestion via native spreadsheet session pipeline.'),
  ('can_manage_users', 'Manage Users', 'Allows managing user accounts.'),
  ('can_create_user', 'Create User', 'Allows creating user accounts.'),
  ('can_edit_user', 'Edit User', 'Allows editing user account details.'),
  ('can_activate_user', 'Activate User', 'Allows activating or deactivating user accounts.'),
  ('can_manage_roles', 'Manage Roles', 'Allows managing roles and permissions.'),
  ('can_manage_workflows', 'Manage Workflows', 'Allows managing workflow configuration.'),
  ('can_manage_departments', 'Manage Departments', 'Allows managing departments.'),
  ('can_manage_shifts', 'Manage Shifts', 'Allows managing shifts.'),
  ('can_manage_machines', 'Manage Machines', 'Allows managing machines.'),
  ('can_manage_task_templates', 'Manage Task Templates', 'Allows managing task templates.'),
  ('can_manage_kpis', 'Manage KPIs', 'Allows managing KPI definitions.'),
  ('can_manage_escalation_rules', 'Manage Escalation Rules', 'Allows managing escalation rules.'),
  ('can_view_reports', 'View Reports', 'Allows viewing reports.'),
  ('can_export_reports', 'Export Reports', 'Allows exporting reports.'),
  ('receive_executive_desktop_notifications', 'Receive Executive Desktop Notifications', 'Allows receiving executive desktop notifications for project release events.'),
  ('control_design.workspace.view', 'View Control Design Workspace', 'Allows entering the Control Design workspace within the Control Design subdivision.'),
  ('control_design.projects.view_assigned', 'View Assigned Control Design Projects', 'Allows viewing Control Design projects assigned to the current user.'),
  ('control_design.projects.view_all', 'View All Control Design Projects', 'Allows viewing all Control Design project workflows in scope.'),
  ('control_design.projects.create', 'Create Control Design Projects', 'Allows creating Control Design project workflows.'),
  ('control_design.projects.edit', 'Edit Control Design Projects', 'Allows editing Control Design project metadata.'),
  ('control_design.projects.assign', 'Assign Control Design Projects', 'Allows assigning Control Design project ownership.'),
  ('control_design.projects.reassign', 'Reassign Control Design Projects', 'Allows reassigning Control Design project ownership.'),
  ('control_design.projects.cancel', 'Cancel Control Design Projects', 'Allows cancelling Control Design projects.'),
  ('control_design.stages.start', 'Start Control Design Stages', 'Allows an assigned owner to start unlocked Control Design stages.'),
  ('control_design.stages.submit', 'Submit Control Design Stages', 'Allows an assigned owner to submit Control Design stages.'),
  ('control_design.paths.update', 'Update Control Design Paths', 'Allows updating Control Design stage document paths.'),
  ('control_design.approvals.review', 'Review Control Design Approvals', 'Allows viewing Control Design approval queues.'),
  ('control_design.approvals.approve', 'Approve Control Design Submissions', 'Allows approving pending Control Design submissions.'),
  ('control_design.approvals.request_changes', 'Request Control Design Changes', 'Allows requesting changes on pending Control Design submissions.'),
  ('control_design.revisions.raise', 'Raise Control Design Revisions', 'Allows raising post-approval Control Design revisions.'),
  ('control_design.revisions.execute', 'Execute Control Design Revisions', 'Allows assigned owners to execute Control Design revisions.'),
  ('control_design.revisions.review', 'Review Control Design Revisions', 'Allows reviewing submitted Control Design revisions.'),
  ('control_design.stages.mark_pre_completed', 'Mark Control Design Stages Pre-Completed', 'Allows marking Control Design stages pre-completed with evidence.'),
  ('control_design.stages.override_unlock', 'Override Unlock Control Design Stages', 'Allows override-unlocking Control Design stages.'),
  ('control_design.stages.skip_override', 'Skip Control Design Stages By Override', 'Allows recording Control Design stages skipped by override.'),
  ('control_design.projects.mark_dispatched', 'Mark Control Design Projects Dispatched', 'Allows marking ready Control Design projects as dispatched.'),
  ('control_design.projects.reopen_after_dispatch', 'Reopen Control Design Projects After Dispatch', 'Allows reopening dispatched Control Design projects.'),
  ('control_design.audit.view', 'View Control Design Audit', 'Allows viewing Control Design audit history.'),
  ('control_design.reports.view', 'View Control Design Reports', 'Allows viewing Control Design reports.')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    updated_at = NOW();
