const {
  AUXILIARY_COLORS,
  MATRIX_STATUS_LABELS,
  STATUS_COLORS,
  buildProgressBar,
  statusColor,
} = require("./designReportManagementModel");

const PAGE = Object.freeze({
  width: 842,
  height: 595,
  margin: 28,
  footerHeight: 24,
});

const THEME = Object.freeze({
  navy: "#0B2A66",
  blue: "#26478B",
  lightBlue: "#DCE6F2",
  panel: "#EDEFF4",
  soft: "#F3F3F3",
  white: "#FFFFFF",
  border: "#B7C3D0",
  text: "#172033",
  muted: "#5B6472",
});

function escapePdfText(value) {
  return String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/\r?\n/g, " ");
}

function hexToRgb(hex) {
  const clean = String(hex || "#000000").replace("#", "");
  const value = parseInt(clean, 16);
  return [
    ((value >> 16) & 255) / 255,
    ((value >> 8) & 255) / 255,
    (value & 255) / 255,
  ];
}

function pdfNumber(value) {
  return Number(value).toFixed(3).replace(/\.?0+$/g, "");
}

function wrapText(value, maxWidth, fontSize) {
  const text = String(value ?? "").replace(/\s+/g, " ").trim();
  if (!text) {
    return [""];
  }

  const maxChars = Math.max(4, Math.floor(maxWidth / (fontSize * 0.52)));
  const words = text.split(" ");
  const lines = [];
  let line = "";

  words.forEach((word) => {
    if (!line) {
      line = word.slice(0, maxChars);
      if (word.length > maxChars) {
        lines.push(line);
        line = word.slice(maxChars);
      }
      return;
    }

    if (`${line} ${word}`.length <= maxChars) {
      line = `${line} ${word}`;
      return;
    }

    lines.push(line);
    line = word.slice(0, maxChars);
  });

  if (line) {
    lines.push(line);
  }

  return lines.length ? lines : [""];
}

class PdfCanvas {
  constructor(model) {
    this.model = model;
    this.pages = [];
    this.current = null;
    this.y = PAGE.margin;
  }

  addPage(title) {
    this.current = [];
    this.pages.push(this.current);
    this.y = PAGE.margin;
    this.rect(0, 0, PAGE.width, 22, THEME.navy);
    this.text("PARC Task Control System", PAGE.margin, 14, {
      size: 9,
      color: THEME.white,
      bold: true,
    });
    this.text(this.model.reportVersion, PAGE.width / 2 - 76, 14, {
      size: 9,
      color: THEME.white,
      bold: true,
    });
    this.text(`Page ${this.pages.length}`, PAGE.width - PAGE.margin - 40, 14, {
      size: 9,
      color: THEME.white,
      bold: true,
    });

    this.y = 34;
    this.text(title, PAGE.margin, this.y, {
      size: 16,
      bold: true,
      color: THEME.navy,
    });
    this.y += 22;
    this.text(`${this.model.context.project_no || ""} | ${this.model.context.project_name || ""}`, PAGE.margin, this.y, {
      size: 9,
      color: THEME.muted,
    });
    this.y += 18;

    this.footer();
  }

  footer() {
    const y = PAGE.height - PAGE.footerHeight;
    this.line(PAGE.margin, y - 6, PAGE.width - PAGE.margin, y - 6, THEME.border);
    const generatedOn = this.model.overview.find((row) => row.label === "Generated Date")?.value || "";
    const footer = `Report Version: ${this.model.reportVersion} | Generated On: ${generatedOn} | Generated By: ${this.model.generatedBy || ""}`;
    this.text(footer, PAGE.margin, y + 8, { size: 7, color: THEME.muted });
  }

  ensureSpace(required, title) {
    if (this.y + required <= PAGE.height - PAGE.footerHeight - 10) {
      return;
    }

    this.addPage(title);
  }

  command(value) {
    this.current.push(value);
  }

  setFill(hex) {
    const [r, g, b] = hexToRgb(hex);
    this.command(`${pdfNumber(r)} ${pdfNumber(g)} ${pdfNumber(b)} rg`);
  }

  setStroke(hex) {
    const [r, g, b] = hexToRgb(hex);
    this.command(`${pdfNumber(r)} ${pdfNumber(g)} ${pdfNumber(b)} RG`);
  }

  rect(x, y, width, height, color, stroke = null) {
    this.setFill(color);
    const pdfY = PAGE.height - y - height;
    this.command(`${pdfNumber(x)} ${pdfNumber(pdfY)} ${pdfNumber(width)} ${pdfNumber(height)} re f`);
    if (stroke) {
      this.setStroke(stroke);
      this.command(`${pdfNumber(x)} ${pdfNumber(pdfY)} ${pdfNumber(width)} ${pdfNumber(height)} re S`);
    }
  }

  line(x1, y1, x2, y2, color = THEME.border) {
    this.setStroke(color);
    this.command(`${pdfNumber(x1)} ${pdfNumber(PAGE.height - y1)} m ${pdfNumber(x2)} ${pdfNumber(PAGE.height - y2)} l S`);
  }

  text(value, x, y, options = {}) {
    const size = options.size || 9;
    const color = options.color || THEME.text;
    const font = options.bold ? "F2" : "F1";
    const [r, g, b] = hexToRgb(color);
    const pdfY = PAGE.height - y;
    this.command("BT");
    this.command(`/${font} ${pdfNumber(size)} Tf`);
    this.command(`${pdfNumber(r)} ${pdfNumber(g)} ${pdfNumber(b)} rg`);
    this.command(`${pdfNumber(x)} ${pdfNumber(pdfY)} Td`);
    this.command(`(${escapePdfText(value)}) Tj`);
    this.command("ET");
  }

  section(title) {
    this.ensureSpace(28, title);
    this.rect(PAGE.margin, this.y, PAGE.width - PAGE.margin * 2, 18, THEME.blue);
    this.text(title, PAGE.margin + 8, this.y + 12, {
      size: 9,
      bold: true,
      color: THEME.white,
    });
    this.y += 24;
  }

  keyValueGrid(items, columns = 2) {
    const gap = 8;
    const cellWidth = (PAGE.width - PAGE.margin * 2 - gap * (columns - 1)) / columns;
    const labelWidth = 112;
    const rowHeight = 24;

    items.forEach((item, index) => {
      if (index % columns === 0) {
        this.ensureSpace(rowHeight, "Executive Summary");
      }
      const column = index % columns;
      const row = Math.floor(index / columns);
      const x = PAGE.margin + column * (cellWidth + gap);
      const y = this.y + (index % columns === 0 ? 0 : -rowHeight * 0);
      this.rect(x, y, labelWidth, rowHeight, THEME.lightBlue, THEME.border);
      this.rect(x + labelWidth, y, cellWidth - labelWidth, rowHeight, THEME.white, THEME.border);
      this.text(item.label, x + 5, y + 15, { size: 7.5, bold: true });
      this.text(item.value || "", x + labelWidth + 5, y + 15, { size: 8 });

      if (column === columns - 1 || index === items.length - 1) {
        this.y += rowHeight;
      }
      if (row < 0) {
        return;
      }
    });
    this.y += 6;
  }

  kpiCards(model) {
    const cards = [
      ["Total Fixtures", model.kpis.totalFixtures, THEME.navy],
      ["Completed", model.kpis.completedFixtures, STATUS_COLORS.Closed],
      ["In Progress", model.kpis.inProgressFixtures, STATUS_COLORS["In Progress"]],
      ["On Hold", model.kpis.onHoldFixtures, STATUS_COLORS["On Hold"]],
      ["Overdue", model.kpis.overdueFixtures, STATUS_COLORS.Overdue],
      ["Released", model.kpis.releasedFixtures, STATUS_COLORS.Closed],
      ["Rework", model.kpis.reworkCount, STATUS_COLORS.Rework],
      ["Review", model.kpis.reviewCount, STATUS_COLORS.Review],
      ["Completion %", model.kpis.completionDisplay, STATUS_COLORS["In Progress"]],
      ["Avg Completion", model.kpis.averageCompletionTime || "N/A", THEME.blue],
    ];
    const cardWidth = (PAGE.width - PAGE.margin * 2 - 4 * 8) / 5;
    const cardHeight = 45;

    cards.forEach((card, index) => {
      if (index === 5) {
        this.y += cardHeight + 8;
      }
      const x = PAGE.margin + (index % 5) * (cardWidth + 8);
      const y = this.y;
      this.rect(x, y, cardWidth, 16, card[2], THEME.border);
      this.rect(x, y + 16, cardWidth, cardHeight - 16, THEME.white, THEME.border);
      this.text(card[0], x + 5, y + 11, { size: 7.5, bold: true, color: THEME.white });
      this.text(card[1], x + 5, y + 35, { size: 14, bold: true, color: THEME.text });
    });

    this.y += cardHeight + 10;
  }

  table(title, columns, rows, options = {}) {
    this.section(title);
    const tableWidth = PAGE.width - PAGE.margin * 2;
    const widths = columns.map((column) => column.width);
    const total = widths.reduce((sum, width) => sum + width, 0);
    const scaled = widths.map((width) => (width / total) * tableWidth);
    const headerHeight = 20;
    const baseRowHeight = options.rowHeight || 22;

    const drawHeader = () => {
      let x = PAGE.margin;
      this.rect(PAGE.margin, this.y, tableWidth, headerHeight, THEME.navy, THEME.navy);
      columns.forEach((column, index) => {
        this.text(column.header, x + 4, this.y + 13, {
          size: 7,
          bold: true,
          color: THEME.white,
        });
        x += scaled[index];
      });
      this.y += headerHeight;
    };

    drawHeader();
    const safeRows = rows.length ? rows : [columns.reduce((acc, column, index) => {
      acc[column.key] = index === 0 ? "No records found" : "";
      return acc;
    }, {})];

    safeRows.forEach((row, rowIndex) => {
      const lineCounts = columns.map((column, index) => (
        wrapText(row[column.key] ?? "", scaled[index] - 8, 7).length
      ));
      const rowHeight = Math.max(baseRowHeight, Math.min(64, Math.max(...lineCounts) * 9 + 8));
      this.ensureSpace(rowHeight + headerHeight, title);
      if (this.y < 90) {
        drawHeader();
      }

      let x = PAGE.margin;
      const rowFill = rowIndex % 2 === 0 ? THEME.white : THEME.soft;
      columns.forEach((column, index) => {
        const value = row[column.key] ?? "";
        const fillColor = column.statusColor && value ? statusColor(value) : rowFill;
        const textColor = column.statusColor && value ? THEME.white : THEME.text;
        this.rect(x, this.y, scaled[index], rowHeight, fillColor, THEME.border);
        const lines = wrapText(value, scaled[index] - 8, 7).slice(0, Math.max(1, Math.floor((rowHeight - 6) / 9)));
        lines.forEach((line, lineIndex) => {
          this.text(line, x + 4, this.y + 11 + lineIndex * 9, {
            size: 7,
            color: textColor,
            bold: Boolean(column.statusColor && value),
          });
        });
        x += scaled[index];
      });
      this.y += rowHeight;
    });

    this.y += 8;
  }
}

function buildPdfBuffer(pages) {
  const objects = [];
  const addObject = (content) => {
    objects.push(content);
    return objects.length;
  };

  const fontRegular = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const fontBold = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
  const pageObjectIds = [];
  const contentObjectIds = [];

  pages.forEach((commands) => {
    const stream = commands.join("\n");
    const contentId = addObject(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
    contentObjectIds.push(contentId);
    pageObjectIds.push(null);
  });

  const pagesId = objects.length + pages.length + 1;
  pages.forEach((_commands, index) => {
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE.width} ${PAGE.height}] /Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentObjectIds[index]} 0 R >>`);
    pageObjectIds[index] = pageId;
  });

  addObject(`<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageObjectIds.length} >>`);
  const catalogId = addObject(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);

  let output = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(output, "utf8"));
    output += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(output, "utf8");
  output += `xref\n0 ${objects.length + 1}\n`;
  output += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    output += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  output += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(output, "utf8");
}

function flattenAuditFixtureRows(fixtureBlock) {
  return fixtureBlock.stages.flatMap((stage) => {
    const rowCount = Math.max(stage.workers.length, stage.proofLinks.length, 1);
    return Array.from({ length: rowCount }, (_unused, index) => {
      const worker = stage.workers[index] || {};
      const proof = stage.proofLinks[index] || null;
      return {
        stageRevision: index === 0 ? `${stage.stage} - ${stage.revision}` : "",
        worker: worker.worker || "",
        contributionPercent: worker.contributionPercent || "Contribution % Not Recorded",
        started: worker.started || "",
        plannedEnd: index === 0 ? stage.plannedEnd : "",
        actualEnd: index === 0 ? stage.actualEnd : "",
        time: index === 0
          ? [stage.plannedTime ? `P ${stage.plannedTime}` : "", stage.actualTime ? `A ${stage.actualTime}` : "", stage.variance ? `V ${stage.variance}` : ""].filter(Boolean).join(" | ")
          : "",
        transferred: index === 0 ? stage.transferred : "",
        proof: proof ? proof.url : (index === 0 ? stage.proofSummary : ""),
      };
    });
  });
}

function generateDesignManagementPdf(model) {
  const pdf = new PdfCanvas(model);

  pdf.addPage("Executive Summary");
  pdf.section("SECTION 1 - PROJECT OVERVIEW");
  pdf.keyValueGrid(model.overview, 2);
  pdf.section("SECTION 2 - PROJECT KPI DASHBOARD");
  pdf.kpiCards(model);
  pdf.table("SECTION 5 - PROGRESS VISUALIZATION", [
    { key: "area", header: "Area", width: 24 },
    { key: "percent", header: "Completion %", width: 16 },
    { key: "bar", header: "Visual Progress Bar", width: 60 },
  ], model.progressVisualization.map((row) => ({
    area: row.area,
    percent: `${row.percent}%`,
    bar: buildProgressBar(row.percent),
  })), { rowHeight: 20 });
  pdf.table("SECTION 12 - PROJECT HEALTH SUMMARY", [
    { key: "indicator", header: "Indicator", width: 22 },
    { key: "value", header: "Value", width: 18, statusColor: true },
    { key: "level", header: "Level", width: 12, statusColor: true },
    { key: "notes", header: "Management Notes", width: 48 },
  ], model.healthSummary, { rowHeight: 24 });

  pdf.addPage("Workflow and Stage Health");
  pdf.table("SECTION 3 - WORKFLOW TIMELINE", [
    { key: "event", header: "Event", width: 24 },
    { key: "date", header: "Date", width: 12 },
    { key: "time", header: "Time", width: 10 },
    { key: "responsibleUser", header: "Responsible User", width: 36 },
    { key: "duration", header: "Duration", width: 18 },
  ], model.workflowTimeline, { rowHeight: 20 });
  pdf.table("SECTION 4 - STAGE HEALTH MATRIX", [
    { key: "stage", header: "Stage", width: 16 },
    ...MATRIX_STATUS_LABELS.map((status) => ({ key: status, header: status, width: 10 })),
  ], model.stageHealthMatrix, { rowHeight: 20 });

  pdf.addPage("Fixture Breakdown");
  pdf.table("SECTION 6 - FIXTURE BREAKDOWN", [
    { key: "fixtureNumber", header: "Fixture Number", width: 15 },
    { key: "fixtureName", header: "Fixture Name", width: 24 },
    { key: "currentStage", header: "Stage", width: 10 },
    { key: "currentStatus", header: "Status", width: 12, statusColor: true },
    { key: "assignedTo", header: "Assigned To", width: 22 },
    { key: "dueDate", header: "Due", width: 10 },
    { key: "actualHours", header: "Actual", width: 9 },
    { key: "plannedHours", header: "Planned", width: 9 },
    { key: "variance", header: "Variance", width: 9 },
    { key: "latestActivity", header: "Latest Activity", width: 30 },
  ], model.fixtureBreakdown, { rowHeight: 24 });
  pdf.table("FIXTURE STAGE DETAILS - CONCEPT / DAP / 3D / 2D", [
    { key: "fixtureNumber", header: "Fixture", width: 14 },
    { key: "globalStatus", header: "Global", width: 11, statusColor: true },
    { key: "conceptStatus", header: "Concept", width: 11, statusColor: true },
    { key: "conceptDuration", header: "Con Dur", width: 9 },
    { key: "dapStatus", header: "DAP", width: 11, statusColor: true },
    { key: "dapDuration", header: "DAP Dur", width: 9 },
    { key: "threeDStatus", header: "3D", width: 11, statusColor: true },
    { key: "threeDDuration", header: "3D Dur", width: 9 },
    { key: "twoDStatus", header: "2D", width: 11, statusColor: true },
    { key: "twoDDuration", header: "2D Dur", width: 9 },
    { key: "twoDProof", header: "2D Proof", width: 12 },
  ], model.fixtureStageDetails, { rowHeight: 26 });

  pdf.addPage("Fixture Stage Execution Audit");
  model.fixtureStageExecutionAudit.forEach((fixtureBlock) => {
    pdf.table(
      `Fixture: ${fixtureBlock.fixtureNumber} | ${fixtureBlock.fixtureName} | Priority: ${fixtureBlock.priority || "Not recorded"}`,
      [
        { key: "stageRevision", header: "Stage / Revision", width: 18 },
        { key: "worker", header: "Worker", width: 24 },
        { key: "contributionPercent", header: "Contribution %", width: 20 },
        { key: "started", header: "Started", width: 15 },
        { key: "plannedEnd", header: "Planned End", width: 15 },
        { key: "actualEnd", header: "Actual End", width: 15 },
        { key: "time", header: "Time P/A/V", width: 18 },
        { key: "transferred", header: "Transferred", width: 10 },
        { key: "proof", header: "Proof Reference", width: 30 },
      ],
      flattenAuditFixtureRows(fixtureBlock),
      { rowHeight: 24 },
    );
  });

  pdf.addPage("Proof and Assignment Analytics");
  pdf.table("SECTION 7 - WORK PROOF ANALYTICS", [
    { key: "fixtureNumber", header: "Fixture", width: 16 },
    { key: "fixtureName", header: "Fixture Name", width: 28 },
    { key: "proofCount", header: "Proof Count", width: 12 },
    { key: "latestUploadDate", header: "Latest Upload", width: 17 },
    { key: "latestUploadedBy", header: "Latest Uploaded By", width: 30 },
    { key: "proofAvailability", header: "Availability", width: 14, statusColor: true },
  ], model.proofAnalytics, { rowHeight: 22 });
  pdf.table("WORK PROOF HISTORY - PROOF REFERENCES", [
    { key: "fixtureNumber", header: "Fixture", width: 14 },
    { key: "stage", header: "Stage", width: 12 },
    { key: "taskId", header: "Task", width: 8 },
    { key: "proofAvailability", header: "Availability", width: 13, statusColor: true },
    { key: "proofLink", header: "Proof Reference", width: 45 },
    { key: "uploadedAt", header: "Uploaded At", width: 15 },
    { key: "uploadedBy", header: "Uploaded By", width: 24 },
  ], model.workProofHistory, { rowHeight: 24 });
  pdf.table("SECTION 10 - ASSIGNMENT HISTORY", [
    { key: "fixtureNumber", header: "Fixture", width: 14 },
    { key: "assignedBy", header: "Assigned By", width: 25 },
    { key: "assignedTo", header: "Assigned To", width: 25 },
    { key: "assignmentDate", header: "Assignment Date", width: 16 },
    { key: "reassignmentDate", header: "Reassignment Date", width: 16 },
    { key: "stage", header: "Stage", width: 12 },
    { key: "comments", header: "Comments", width: 34 },
  ], model.assignmentHistory, { rowHeight: 22 });

  pdf.addPage("Rework, Holds, and Activity");
  pdf.table("SECTION 8 - REWORK ANALYTICS", [
    { key: "stage", header: "Stage", width: 12 },
    { key: "reworkReason", header: "Reason", width: 28 },
    { key: "initiatedBy", header: "Initiated By", width: 28 },
    { key: "date", header: "Date", width: 16 },
    { key: "durationImpact", header: "Impact", width: 12 },
    { key: "comments", header: "Comments", width: 36 },
  ], model.reworkAnalytics.rows, { rowHeight: 24 });
  pdf.table("SECTION 9 - HOLD HISTORY", [
    { key: "fixtureNumber", header: "Fixture", width: 14 },
    { key: "date", header: "Date", width: 16 },
    { key: "stage", header: "Stage", width: 10 },
    { key: "reason", header: "Reason", width: 25 },
    { key: "heldBy", header: "Held By", width: 24 },
    { key: "releasedBy", header: "Released By", width: 24 },
    { key: "holdDuration", header: "Duration", width: 12 },
    { key: "comments", header: "Comments", width: 34 },
  ], model.holdHistory, { rowHeight: 22 });
  pdf.table("SECTION 11 - PROJECT ACTIVITY LOG", [
    { key: "timestamp", header: "Timestamp", width: 16 },
    { key: "fixtureNumber", header: "Fixture", width: 14 },
    { key: "user", header: "User", width: 26 },
    { key: "action", header: "Action", width: 20 },
    { key: "description", header: "Description", width: 54 },
  ], model.activityLog, { rowHeight: 22 });

  pdf.addPage("Report Notes");
  pdf.table("DATABASE QUERIES USED", [
    { key: "note", header: "Query Source", width: 100 },
  ], model.databaseQuerySummary.map((note) => ({ note })), { rowHeight: 22 });
  pdf.table("PERFORMANCE NOTES", [
    { key: "note", header: "Note", width: 100 },
  ], [
    { note: "Report data is loaded through batched project, fixture, workflow, task, attachment, revision, contribution, and completion-truth reads." },
    { note: "Worker contribution percentages are not guessed from elapsed time. Missing contribution truth is displayed as Contribution % Not Recorded." },
    { note: "Task reassignment activity/audit metadata records stage, revision, previous assignee, new assignee, current completion percent, and remaining percent for future audits." },
    { note: "The v2 presentation layer is read-only and does not mutate workflow, RBAC, assignment, revision, or historical records." },
    { note: "Excel and PDF exports are produced from the same management report model to keep content parity across formats." },
  ], { rowHeight: 24 });

  return buildPdfBuffer(pdf.pages);
}

module.exports = {
  generateDesignManagementPdf,
};
