const ExcelJS = require("exceljs");
const {
  AUXILIARY_COLORS,
  MATRIX_STATUS_LABELS,
  STATUS_COLORS,
  buildProgressBar,
  statusColor,
} = require("./designReportManagementModel");

const THEME = Object.freeze({
  navy: "0B2A66",
  blue: "26478B",
  lightBlue: "DCE6F2",
  panel: "EDEFF4",
  soft: "F3F3F3",
  white: "FFFFFF",
  border: "B7C3D0",
  text: "172033",
});

const MANAGED_SHEET_NAMES = [
  "Executive Summary",
  "Workflow Analytics",
  "Stage Analytics",
  "Fixture Breakdown",
  "Fixture Stage Details",
  "Stage Execution Audit",
  "Proof Analytics",
  "Assignments",
  "Work Proof History",
  "Hold History",
  "Rework History",
  "Activity Timeline",
  "Report Notes",
];

function argb(hex) {
  return `FF${String(hex || "").replace("#", "")}`;
}

function fill(hex) {
  return {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: argb(hex) },
  };
}

function border(color = THEME.border) {
  return {
    top: { style: "thin", color: { argb: argb(color) } },
    left: { style: "thin", color: { argb: argb(color) } },
    bottom: { style: "thin", color: { argb: argb(color) } },
    right: { style: "thin", color: { argb: argb(color) } },
  };
}

function styleReportSheet(worksheet, model) {
  worksheet.properties.defaultRowHeight = 18;
  worksheet.pageSetup = {
    orientation: "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    margins: {
      left: 0.35,
      right: 0.35,
      top: 0.5,
      bottom: 0.55,
      header: 0.25,
      footer: 0.25,
    },
  };
  worksheet.headerFooter.oddFooter = `&LPARC Task Control System&C${model.reportVersion} | Generated On ${model.overview.find((row) => row.label === "Generated Date")?.value || ""}&RGenerated By ${model.generatedBy || ""} | Page &P`;
}

function mergeTitle(worksheet, title, subtitle, lastColumn = "N") {
  worksheet.mergeCells(`A1:${lastColumn}1`);
  const titleCell = worksheet.getCell("A1");
  titleCell.value = title;
  titleCell.fill = fill(THEME.navy);
  titleCell.font = { color: { argb: argb(THEME.white) }, bold: true, size: 16 };
  titleCell.alignment = { vertical: "middle", horizontal: "center" };
  worksheet.getRow(1).height = 28;

  worksheet.mergeCells(`A2:${lastColumn}2`);
  const subtitleCell = worksheet.getCell("A2");
  subtitleCell.value = subtitle;
  subtitleCell.fill = fill(THEME.blue);
  subtitleCell.font = { color: { argb: argb(THEME.white) }, bold: true, size: 10 };
  subtitleCell.alignment = { vertical: "middle", horizontal: "center" };
  worksheet.getRow(2).height = 18;
}

function addSectionHeader(worksheet, rowNumber, title, lastColumn = "N") {
  worksheet.mergeCells(`A${rowNumber}:${lastColumn}${rowNumber}`);
  const cell = worksheet.getCell(`A${rowNumber}`);
  cell.value = title;
  cell.fill = fill(THEME.blue);
  cell.font = { color: { argb: argb(THEME.white) }, bold: true, size: 11 };
  cell.alignment = { vertical: "middle", horizontal: "left" };
  cell.border = border(THEME.blue);
  worksheet.getRow(rowNumber).height = 22;
}

function writeKeyValueGrid(worksheet, startRow, startColumn, rows, pairsPerRow = 2) {
  const labelFill = fill(THEME.lightBlue);
  const valueFill = fill(THEME.white);
  rows.forEach((item, index) => {
    const rowOffset = Math.floor(index / pairsPerRow);
    const pairOffset = index % pairsPerRow;
    const labelColumn = startColumn + pairOffset * 4;
    const valueColumn = labelColumn + 1;
    const rowNumber = startRow + rowOffset;
    const labelCell = worksheet.getCell(rowNumber, labelColumn);
    const valueCell = worksheet.getCell(rowNumber, valueColumn);

    worksheet.mergeCells(rowNumber, valueColumn, rowNumber, valueColumn + 2);

    labelCell.value = item.label;
    labelCell.fill = labelFill;
    labelCell.font = { bold: true, color: { argb: argb(THEME.text) }, size: 9 };
    labelCell.alignment = { vertical: "middle", horizontal: "left", wrapText: true };
    labelCell.border = border();

    valueCell.value = item.value || "";
    valueCell.fill = valueFill;
    valueCell.font = { color: { argb: argb(THEME.text) }, size: 9 };
    valueCell.alignment = { vertical: "middle", horizontal: "left", wrapText: true };
    valueCell.border = border();

    for (let column = valueColumn + 1; column <= valueColumn + 2; column += 1) {
      worksheet.getCell(rowNumber, column).border = border();
      worksheet.getCell(rowNumber, column).fill = valueFill;
    }
    worksheet.getRow(rowNumber).height = 24;
  });

  return startRow + Math.ceil(rows.length / pairsPerRow);
}

function writeKpiCards(worksheet, startRow, model) {
  const cards = [
    { label: "Total Fixtures", value: model.kpis.totalFixtures, color: THEME.navy },
    { label: "Completed Fixtures", value: model.kpis.completedFixtures, color: STATUS_COLORS.Closed },
    { label: "In Progress Fixtures", value: model.kpis.inProgressFixtures, color: STATUS_COLORS["In Progress"] },
    { label: "On Hold Fixtures", value: model.kpis.onHoldFixtures, color: STATUS_COLORS["On Hold"] },
    { label: "Overdue Fixtures", value: model.kpis.overdueFixtures, color: STATUS_COLORS.Overdue },
    { label: "Released Fixtures", value: model.kpis.releasedFixtures, color: STATUS_COLORS.Closed },
    { label: "Rework Count", value: model.kpis.reworkCount, color: STATUS_COLORS.Rework },
    { label: "Review Count", value: model.kpis.reviewCount, color: STATUS_COLORS.Review },
    { label: "Completion %", value: model.kpis.completionDisplay, color: STATUS_COLORS["In Progress"] },
    { label: "Average Completion Time", value: model.kpis.averageCompletionTime || "N/A", color: THEME.blue },
  ];

  cards.forEach((card, index) => {
    const rowOffset = Math.floor(index / 5) * 3;
    const columnOffset = (index % 5) * 3 + 1;
    const row = startRow + rowOffset;
    worksheet.mergeCells(row, columnOffset, row, columnOffset + 2);
    worksheet.mergeCells(row + 1, columnOffset, row + 2, columnOffset + 2);
    const labelCell = worksheet.getCell(row, columnOffset);
    const valueCell = worksheet.getCell(row + 1, columnOffset);
    labelCell.value = card.label;
    labelCell.fill = fill(card.color);
    labelCell.font = { color: { argb: argb(THEME.white) }, bold: true, size: 9 };
    labelCell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    labelCell.border = border(card.color);
    valueCell.value = card.value;
    valueCell.fill = fill(THEME.white);
    valueCell.font = { bold: true, size: 16, color: { argb: argb(THEME.text) } };
    valueCell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    valueCell.border = border(card.color);
    for (let c = columnOffset + 1; c <= columnOffset + 2; c += 1) {
      worksheet.getCell(row, c).fill = fill(card.color);
      worksheet.getCell(row, c).border = border(card.color);
      worksheet.getCell(row + 1, c).fill = fill(THEME.white);
      worksheet.getCell(row + 1, c).border = border(card.color);
      worksheet.getCell(row + 2, c).fill = fill(THEME.white);
      worksheet.getCell(row + 2, c).border = border(card.color);
    }
  });

  return startRow + 6;
}

function writeSmallTable(worksheet, startRow, startColumn, columns, rows, options = {}) {
  const safeRows = rows.length ? rows : [columns.reduce((acc, column, index) => {
    acc[column.key] = index === 0 ? "No records found" : "";
    return acc;
  }, {})];
  const headerRow = worksheet.getRow(startRow);
  columns.forEach((column, index) => {
    const cell = headerRow.getCell(startColumn + index);
    cell.value = column.header;
    cell.fill = fill(THEME.navy);
    cell.font = { color: { argb: argb(THEME.white) }, bold: true, size: 9 };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = border(THEME.navy);
  });
  headerRow.height = 24;

  safeRows.forEach((row, rowIndex) => {
    const excelRow = worksheet.getRow(startRow + rowIndex + 1);
    columns.forEach((column, columnIndex) => {
      const cell = excelRow.getCell(startColumn + columnIndex);
      const value = row[column.key] ?? "";
      if (column.hyperlinkKey && row[column.hyperlinkKey]) {
        cell.value = {
          text: value || "View",
          hyperlink: row[column.hyperlinkKey],
        };
        cell.font = { size: 9, color: { argb: "FF1D4ED8" }, underline: true };
      } else {
        cell.value = value;
        cell.font = { size: 9, color: { argb: argb(THEME.text) } };
      }
      cell.fill = fill(rowIndex % 2 === 0 ? THEME.white : THEME.soft);
      cell.alignment = { vertical: "middle", horizontal: column.align || "left", wrapText: true };
      cell.border = border();

      if (column.statusColor && !(column.hyperlinkKey && row[column.hyperlinkKey])) {
        const color = statusColor(value);
        cell.fill = fill(color);
        cell.font = { size: 9, bold: true, color: { argb: argb(THEME.white) } };
        cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
      }

      if (options.matrix && MATRIX_STATUS_LABELS.includes(column.header) && Number(value) > 0) {
        cell.fill = fill(statusColor(column.header));
        cell.font = { size: 9, bold: true, color: { argb: argb(THEME.white) } };
        cell.alignment = { vertical: "middle", horizontal: "center" };
      }
    });
    excelRow.height = options.rowHeight || 24;
  });

  return startRow + safeRows.length + 1;
}

function addStatusConditionalFormatting(worksheet, columnLetter, startRow, endRow) {
  if (endRow < startRow) {
    return;
  }

  Object.entries({ ...STATUS_COLORS, ...AUXILIARY_COLORS }).forEach(([status, color]) => {
    worksheet.addConditionalFormatting({
      ref: `${columnLetter}${startRow}:${columnLetter}${endRow}`,
      rules: [{
        type: "containsText",
        operator: "containsText",
        text: status,
        priority: 1,
        style: {
          fill: fill(color),
          font: { color: { argb: argb(THEME.white) }, bold: true },
        },
      }],
    });
  });
}

function autoWidth(worksheet, columns) {
  columns.forEach((column, index) => {
    const excelColumn = worksheet.getColumn(index + 1);
    excelColumn.width = column.width || 16;
  });
}

function addTableSheet(workbook, model, config) {
  const worksheet = workbook.addWorksheet(config.name);
  styleReportSheet(worksheet, model);
  mergeTitle(worksheet, config.title, `${model.context.project_no || ""} | ${model.context.project_name || ""}`, config.lastColumn || "L");
  const headerRowNumber = 4;
  worksheet.views = [{ state: "frozen", ySplit: headerRowNumber }];
  worksheet.autoFilter = {
    from: { row: headerRowNumber, column: 1 },
    to: { row: headerRowNumber, column: config.columns.length },
  };

  writeSmallTable(worksheet, headerRowNumber, 1, config.columns, config.rows, { rowHeight: config.rowHeight || 30 });
  autoWidth(worksheet, config.columns);

  config.columns.forEach((column, index) => {
    if (column.statusColor) {
      const letter = worksheet.getColumn(index + 1).letter;
      addStatusConditionalFormatting(worksheet, letter, headerRowNumber + 1, headerRowNumber + Math.max(1, config.rows.length));
    }
  });

  return worksheet;
}

function addExecutiveSummary(workbook, model) {
  const worksheet = workbook.addWorksheet("Executive Summary");
  styleReportSheet(worksheet, model);
  worksheet.views = [{ state: "frozen", ySplit: 3 }];
  worksheet.columns = Array.from({ length: 14 }, () => ({ width: 14 }));

  mergeTitle(
    worksheet,
    "Executive Project Summary",
    `${model.reportVersion} | ${model.context.project_no || ""} | ${model.context.project_name || ""}`,
    "N",
  );

  addSectionHeader(worksheet, 4, "SECTION 1 - PROJECT OVERVIEW", "N");
  const nextAfterOverview = writeKeyValueGrid(worksheet, 5, 1, model.overview, 2);

  addSectionHeader(worksheet, nextAfterOverview + 1, "SECTION 2 - PROJECT KPI DASHBOARD", "N");
  const nextAfterKpis = writeKpiCards(worksheet, nextAfterOverview + 2, model);

  addSectionHeader(worksheet, nextAfterKpis + 1, "SECTION 3 - WORKFLOW TIMELINE", "N");
  const timelineColumns = [
    { key: "event", header: "Event", width: 22 },
    { key: "date", header: "Date", width: 12, align: "center" },
    { key: "time", header: "Time", width: 10, align: "center" },
    { key: "responsibleUser", header: "Responsible User", width: 28 },
    { key: "duration", header: "Duration", width: 14, align: "center" },
  ];
  const timelineEnd = writeSmallTable(worksheet, nextAfterKpis + 2, 1, timelineColumns, model.workflowTimeline, { rowHeight: 24 });

  addSectionHeader(worksheet, timelineEnd + 1, "SECTION 4 - STAGE HEALTH MATRIX", "N");
  const matrixColumns = [
    { key: "stage", header: "Stage", width: 14 },
    ...MATRIX_STATUS_LABELS.map((status) => ({ key: status, header: status, width: 13, align: "center" })),
  ];
  const matrixEnd = writeSmallTable(worksheet, timelineEnd + 2, 1, matrixColumns, model.stageHealthMatrix, {
    rowHeight: 24,
    matrix: true,
  });

  addSectionHeader(worksheet, matrixEnd + 1, "SECTION 5 - PROGRESS VISUALIZATION", "N");
  const progressRows = model.progressVisualization.map((row) => ({
    area: row.area,
    percent: row.percent,
    bar: buildProgressBar(row.percent),
  }));
  const progressEnd = writeSmallTable(worksheet, matrixEnd + 2, 1, [
    { key: "area", header: "Area", width: 20 },
    { key: "percent", header: "Completion %", width: 14, align: "center" },
    { key: "bar", header: "Visual Progress Bar", width: 36 },
  ], progressRows, { rowHeight: 24 });

  addSectionHeader(worksheet, progressEnd + 1, "SECTION 12 - PROJECT HEALTH SUMMARY", "N");
  writeSmallTable(worksheet, progressEnd + 2, 1, [
    { key: "indicator", header: "Indicator", width: 24 },
    { key: "value", header: "Value", width: 20, statusColor: true },
    { key: "level", header: "Level", width: 12, statusColor: true },
    { key: "notes", header: "Management Notes", width: 52 },
  ], model.healthSummary, { rowHeight: 28 });

  return worksheet;
}

function getAuditRowsForStage(stage) {
  const rowCount = Math.max(stage.workers.length, stage.proofLinks.length, 1);
  return Array.from({ length: rowCount }, (_unused, index) => {
    const worker = stage.workers[index] || {};
    const proof = stage.proofLinks[index] || null;
    const notes = [
      stage.revisionReason ? `Revision reason: ${stage.revisionReason}` : "",
      worker.transferReason ? `Transfer reason: ${worker.transferReason}` : "",
      worker.transferredBy ? `Transferred by: ${worker.transferredBy}` : "",
      worker.transferredAt ? `Transferred at: ${worker.transferredAt}` : "",
      proof?.uploadedBy ? `Uploaded by: ${proof.uploadedBy}` : "",
      proof?.uploadedAt ? `Uploaded at: ${proof.uploadedAt}` : "",
    ].filter(Boolean).join(" | ");

    return {
      stage: index === 0 ? stage.stage : "",
      revision: index === 0 ? stage.revision : "",
      worker: worker.worker || "",
      contributionPercent: worker.contributionPercent || "Contribution % Not Recorded",
      started: worker.started || "",
      plannedStart: index === 0 ? stage.plannedStart : "",
      plannedEnd: index === 0 ? stage.plannedEnd : "",
      actualEnd: index === 0 ? stage.actualEnd : "",
      plannedTime: index === 0 ? stage.plannedTime : "",
      actualTime: index === 0 ? stage.actualTime : "",
      variance: index === 0 ? stage.variance : "",
      transferred: index === 0 ? stage.transferred : "",
      priority: index === 0 ? stage.priority : "",
      proofText: proof ? `${proof.label}: ${proof.url}` : (index === 0 ? stage.proofSummary : ""),
      proofUrl: proof?.url || "",
      notes,
    };
  });
}

function addFixtureStageExecutionAuditSheet(workbook, model) {
  const worksheet = workbook.addWorksheet("Stage Execution Audit");
  styleReportSheet(worksheet, model);
  mergeTitle(
    worksheet,
    "FIXTURE STAGE EXECUTION AUDIT",
    "Project -> Fixture -> Stage -> Revision -> Worker Contribution -> Proof Images",
    "O",
  );
  worksheet.views = [{ state: "frozen", ySplit: 3 }];

  const columns = [
    { key: "stage", header: "Stage", width: 14 },
    { key: "revision", header: "Revision", width: 14 },
    { key: "worker", header: "Worker", width: 30 },
    { key: "contributionPercent", header: "Contribution %", width: 24 },
    { key: "started", header: "Started", width: 18 },
    { key: "plannedStart", header: "Planned Start", width: 18 },
    { key: "plannedEnd", header: "Planned End", width: 18 },
    { key: "actualEnd", header: "Actual End", width: 18 },
    { key: "plannedTime", header: "Planned Time", width: 14 },
    { key: "actualTime", header: "Actual Time", width: 14 },
    { key: "variance", header: "Variance", width: 12 },
    { key: "transferred", header: "Transferred", width: 12 },
    { key: "priority", header: "Priority", width: 12 },
    { key: "proofText", header: "Proof Images", width: 42 },
    { key: "notes", header: "Audit Notes", width: 52 },
  ];
  autoWidth(worksheet, columns);

  let rowNumber = 4;
  model.fixtureStageExecutionAudit.forEach((fixtureBlock) => {
    worksheet.mergeCells(rowNumber, 1, rowNumber, columns.length);
    const fixtureCell = worksheet.getCell(rowNumber, 1);
    fixtureCell.value = `Fixture: ${fixtureBlock.fixtureNumber} | ${fixtureBlock.fixtureName} | Priority: ${fixtureBlock.priority || "Not recorded"} | Status: ${fixtureBlock.currentStatus} | Current Stage: ${fixtureBlock.currentStage}`;
    fixtureCell.fill = fill(THEME.navy);
    fixtureCell.font = { color: { argb: argb(THEME.white) }, bold: true, size: 11 };
    fixtureCell.alignment = { vertical: "middle", horizontal: "left", wrapText: true };
    fixtureCell.border = border(THEME.navy);
    worksheet.getRow(rowNumber).height = 24;
    rowNumber += 1;

    const headerRow = worksheet.getRow(rowNumber);
    columns.forEach((column, index) => {
      const cell = headerRow.getCell(index + 1);
      cell.value = column.header;
      cell.fill = fill(THEME.blue);
      cell.font = { color: { argb: argb(THEME.white) }, bold: true, size: 9 };
      cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
      cell.border = border(THEME.blue);
    });
    headerRow.height = 24;
    rowNumber += 1;

    fixtureBlock.stages.forEach((stage) => {
      getAuditRowsForStage(stage).forEach((row, rowIndex) => {
        const excelRow = worksheet.getRow(rowNumber);
        columns.forEach((column, columnIndex) => {
          const cell = excelRow.getCell(columnIndex + 1);
          if (column.key === "proofText" && row.proofUrl) {
            cell.value = {
              text: row.proofText,
              hyperlink: row.proofUrl,
            };
            cell.font = { size: 9, color: { argb: "FF1D4ED8" }, underline: true };
          } else {
            cell.value = row[column.key] || "";
            cell.font = { size: 9, color: { argb: argb(THEME.text) } };
          }
          cell.fill = fill(rowIndex % 2 === 0 ? THEME.white : THEME.soft);
          cell.alignment = { vertical: "top", horizontal: ["plannedTime", "actualTime", "variance", "transferred"].includes(column.key) ? "center" : "left", wrapText: true };
          cell.border = border();
        });
        excelRow.height = 34;
        rowNumber += 1;
      });
    });

    rowNumber += 1;
  });

  return worksheet;
}

function addWorkbookMetadata(workbook, model) {
  workbook.creator = "PARC Task Control System";
  workbook.lastModifiedBy = "PARC Task Control System";
  workbook.created = model.generatedAt instanceof Date ? model.generatedAt : new Date(model.generatedAt);
  workbook.modified = new Date();
  workbook.subject = model.reportVersion;
  workbook.title = `${model.context.project_no || ""} Project Report`;
}

function removeManagedSheets(workbook) {
  MANAGED_SHEET_NAMES.forEach((sheetName) => {
    const worksheet = workbook.getWorksheet(sheetName);
    if (worksheet) {
      workbook.removeWorksheet(worksheet.id);
    }
  });
}

function reorderWorkbookSheets(workbook) {
  const templateSheet = workbook.worksheets.find((worksheet) => (
    worksheet.name.toLowerCase().startsWith("design project execution")
  ));
  const preferredOrder = [
    "Executive Summary",
    templateSheet?.name,
    "Stage Execution Audit",
    "Fixture Stage Details",
    "Fixture Breakdown",
    "Work Proof History",
    "Assignments",
    "Hold History",
    "Rework History",
    "Activity Timeline",
    "Workflow Analytics",
    "Stage Analytics",
    "Proof Analytics",
    "Report Notes",
  ].filter(Boolean);
  const ordered = new Set(preferredOrder);

  preferredOrder.forEach((sheetName, index) => {
    const worksheet = workbook.getWorksheet(sheetName);
    if (worksheet) {
      worksheet.orderNo = index;
    }
  });

  let orderNo = preferredOrder.length;
  workbook.worksheets.forEach((worksheet) => {
    if (!ordered.has(worksheet.name)) {
      worksheet.orderNo = orderNo;
      orderNo += 1;
    }
  });
}

async function generateDesignManagementExcel({ model, filePath, appendToExistingWorkbook = false }) {
  const workbook = new ExcelJS.Workbook();
  if (appendToExistingWorkbook) {
    await workbook.xlsx.readFile(filePath);
    removeManagedSheets(workbook);
  }

  addWorkbookMetadata(workbook, model);
  addExecutiveSummary(workbook, model);

  addTableSheet(workbook, model, {
    name: "Workflow Analytics",
    title: "WORKFLOW ANALYTICS",
    lastColumn: "E",
    rowHeight: 26,
    columns: [
      { key: "event", header: "Event", width: 24 },
      { key: "date", header: "Date", width: 12, align: "center" },
      { key: "time", header: "Time", width: 10, align: "center" },
      { key: "responsibleUser", header: "Responsible User", width: 32 },
      { key: "duration", header: "Duration", width: 14, align: "center" },
    ],
    rows: model.workflowTimeline,
  });

  addTableSheet(workbook, model, {
    name: "Stage Analytics",
    title: "STAGE ANALYTICS - HEALTH MATRIX",
    lastColumn: "I",
    rowHeight: 26,
    columns: [
      { key: "stage", header: "Stage", width: 14 },
      ...MATRIX_STATUS_LABELS.map((status) => ({ key: status, header: status, width: 13, align: "center" })),
    ],
    rows: model.stageHealthMatrix,
  });

  addTableSheet(workbook, model, {
    name: "Fixture Breakdown",
    title: "SECTION 6 - FIXTURE BREAKDOWN",
    lastColumn: "N",
    rowHeight: 34,
    columns: [
      { key: "fixtureNumber", header: "Fixture Number", width: 18 },
      { key: "fixtureName", header: "Fixture Name", width: 34 },
      { key: "currentStage", header: "Current Stage", width: 16 },
      { key: "currentStatus", header: "Current Status", width: 18, statusColor: true },
      { key: "assignedTo", header: "Assigned To", width: 28 },
      { key: "assignedBy", header: "Assigned By", width: 28 },
      { key: "startDate", header: "Start Date", width: 12 },
      { key: "dueDate", header: "Due Date", width: 12 },
      { key: "completionDate", header: "Completion Date", width: 14 },
      { key: "actualHours", header: "Actual Hours", width: 14 },
      { key: "plannedHours", header: "Planned Hours", width: 14 },
      { key: "variance", header: "Variance", width: 12 },
      { key: "overdueDays", header: "Overdue Days", width: 14 },
      { key: "latestActivity", header: "Latest Activity", width: 36 },
    ],
    rows: model.fixtureBreakdown,
  });

  addTableSheet(workbook, model, {
    name: "Fixture Stage Details",
    title: "FIXTURE STAGE DETAILS - CONCEPT / DAP / 3D / 2D",
    lastColumn: "AJ",
    rowHeight: 44,
    columns: [
      { key: "fixtureNumber", header: "Fixture Number", width: 18 },
      { key: "fixtureName", header: "Fixture Name", width: 34 },
      { key: "globalStatus", header: "Global Status", width: 16, statusColor: true },
      { key: "currentStage", header: "Current Stage", width: 16 },
      { key: "assignedTo", header: "Assigned To", width: 28 },
      { key: "conceptStatus", header: "Concept Status", width: 16, statusColor: true },
      { key: "conceptTimeline", header: "Concept Timeline", width: 26 },
      { key: "conceptDuration", header: "Concept Duration", width: 14 },
      { key: "conceptAssignedTo", header: "Concept Assigned To", width: 24 },
      { key: "conceptRevision", header: "Concept Revision", width: 26 },
      { key: "conceptProof", header: "Concept Proof", width: 16, hyperlinkKey: "conceptProofUrl" },
      { key: "dapStatus", header: "DAP Status", width: 16, statusColor: true },
      { key: "dapTimeline", header: "DAP Timeline", width: 26 },
      { key: "dapDuration", header: "DAP Duration", width: 14 },
      { key: "dapAssignedTo", header: "DAP Assigned To", width: 24 },
      { key: "dapRevision", header: "DAP Revision", width: 26 },
      { key: "dapProof", header: "DAP Proof", width: 16, hyperlinkKey: "dapProofUrl" },
      { key: "threeDStatus", header: "3D Status", width: 16, statusColor: true },
      { key: "threeDTimeline", header: "3D Timeline", width: 26 },
      { key: "threeDDuration", header: "3D Duration", width: 14 },
      { key: "threeDAssignedTo", header: "3D Assigned To", width: 24 },
      { key: "threeDRevision", header: "3D Revision", width: 26 },
      { key: "threeDProof", header: "3D Proof", width: 16, hyperlinkKey: "threeDProofUrl" },
      { key: "twoDStatus", header: "2D Status", width: 16, statusColor: true },
      { key: "twoDTimeline", header: "2D Timeline", width: 26 },
      { key: "twoDDuration", header: "2D Duration", width: 14 },
      { key: "twoDAssignedTo", header: "2D Assigned To", width: 24 },
      { key: "twoDRevision", header: "2D Revision", width: 26 },
      { key: "twoDProof", header: "2D Proof", width: 16, hyperlinkKey: "twoDProofUrl" },
      { key: "plannedHours", header: "Planned Hours", width: 14 },
      { key: "actualHours", header: "Actual Hours", width: 14 },
      { key: "variance", header: "Variance", width: 12 },
    ],
    rows: model.fixtureStageDetails,
  });

  addFixtureStageExecutionAuditSheet(workbook, model);

  addTableSheet(workbook, model, {
    name: "Proof Analytics",
    title: "SECTION 7 - WORK PROOF ANALYTICS",
    lastColumn: "G",
    rowHeight: 30,
    columns: [
      { key: "fixtureNumber", header: "Fixture Number", width: 18 },
      { key: "fixtureName", header: "Fixture Name", width: 34 },
      { key: "proofCount", header: "Proof Count", width: 12, align: "center" },
      { key: "latestUploadDate", header: "Latest Upload Date", width: 18 },
      { key: "latestUploadedBy", header: "Latest Uploaded By", width: 28 },
      { key: "firstUploadDate", header: "First Upload Date", width: 18 },
      { key: "proofAvailability", header: "Proof Availability", width: 18, statusColor: true },
    ],
    rows: model.proofAnalytics,
  });

  addTableSheet(workbook, model, {
    name: "Assignments",
    title: "SECTION 10 - ASSIGNMENT HISTORY",
    lastColumn: "H",
    rowHeight: 32,
    columns: [
      { key: "fixtureNumber", header: "Fixture Number", width: 18 },
      { key: "assignedBy", header: "Assigned By", width: 28 },
      { key: "assignedTo", header: "Assigned To", width: 28 },
      { key: "assignmentDate", header: "Assignment Date", width: 18 },
      { key: "reassignmentDate", header: "Reassignment Date", width: 18 },
      { key: "stage", header: "Stage", width: 14 },
      { key: "revision", header: "Revision", width: 14 },
      { key: "comments", header: "Comments", width: 42 },
    ],
    rows: model.assignmentHistory,
  });

  addTableSheet(workbook, model, {
    name: "Work Proof History",
    title: "WORK PROOF HISTORY - CLICKABLE PROOF LINKS",
    lastColumn: "J",
    rowHeight: 32,
    columns: [
      { key: "fixtureNumber", header: "Fixture Number", width: 18 },
      { key: "fixtureName", header: "Fixture Name", width: 34 },
      { key: "stage", header: "Stage", width: 14 },
      { key: "taskId", header: "Task ID", width: 10 },
      { key: "proofNumber", header: "Proof No", width: 10, align: "center" },
      { key: "proofAvailability", header: "Availability", width: 16, statusColor: true },
      { key: "proofLink", header: "Proof Link", width: 24, hyperlinkKey: "proofLink" },
      { key: "uploadedAt", header: "Uploaded At", width: 18 },
      { key: "uploadedBy", header: "Uploaded By", width: 28 },
      { key: "source", header: "Source", width: 22 },
    ],
    rows: model.workProofHistory,
  });

  addTableSheet(workbook, model, {
    name: "Hold History",
    title: "SECTION 9 - HOLD HISTORY",
    lastColumn: "H",
    rowHeight: 32,
    columns: [
      { key: "fixtureNumber", header: "Fixture Number", width: 18 },
      { key: "date", header: "Date", width: 18 },
      { key: "stage", header: "Stage", width: 12 },
      { key: "reason", header: "Reason", width: 28 },
      { key: "heldBy", header: "Held By", width: 28 },
      { key: "releasedBy", header: "Released By", width: 28 },
      { key: "holdDuration", header: "Hold Duration", width: 16 },
      { key: "comments", header: "Comments", width: 42 },
    ],
    rows: model.holdHistory,
  });

  addTableSheet(workbook, model, {
    name: "Rework History",
    title: "SECTION 8 - REWORK HISTORY",
    lastColumn: "H",
    rowHeight: 32,
    columns: [
      { key: "stage", header: "Stage", width: 12 },
      { key: "reworkReason", header: "Rework Reason", width: 26 },
      { key: "initiatedBy", header: "Initiated By", width: 28 },
      { key: "date", header: "Date", width: 18 },
      { key: "durationImpact", header: "Duration Impact", width: 16 },
      { key: "revision", header: "Revision", width: 14 },
      { key: "comments", header: "Comments", width: 42 },
    ],
    rows: model.reworkAnalytics.rows,
  });

  addTableSheet(workbook, model, {
    name: "Activity Timeline",
    title: "SECTION 11 - PROJECT ACTIVITY TIMELINE",
    lastColumn: "E",
    rowHeight: 32,
    columns: [
      { key: "timestamp", header: "Timestamp", width: 18 },
      { key: "fixtureNumber", header: "Fixture Number", width: 18 },
      { key: "user", header: "User", width: 28 },
      { key: "action", header: "Action", width: 22 },
      { key: "description", header: "Description", width: 60 },
    ],
    rows: model.activityLog,
  });

  const dbSheet = addTableSheet(workbook, model, {
    name: "Report Notes",
    title: "DATABASE QUERIES USED AND PERFORMANCE NOTES",
    lastColumn: "B",
    rowHeight: 30,
    columns: [
      { key: "type", header: "Type", width: 24 },
      { key: "note", header: "Note", width: 110 },
    ],
    rows: [
      ...model.databaseQuerySummary.map((note) => ({ type: "Query Source", note })),
      { type: "Performance", note: "Report data is loaded in batched project/fixture/task queries; no per-fixture database calls are introduced by the v2 presentation layer." },
      { type: "Data Accuracy", note: "Worker contribution percentages are displayed only when stored in contribution rows or exact reassignment contribution metadata; otherwise the report displays Contribution % Not Recorded." },
      { type: "Database Enhancement", note: "Task reassignment activity/audit metadata now records stage, revision, previous assignee, new assignee, current task completion percent, and remaining percent for future fixture-stage execution audits." },
      { type: "Compatibility", note: "Report generation is read-only and does not mutate workflow, RBAC, assignment, revision, or historical records." },
    ],
  });
  dbSheet.views = [{ state: "frozen", ySplit: 4 }];

  reorderWorkbookSheets(workbook);
  await workbook.xlsx.writeFile(filePath);
}

module.exports = {
  generateDesignManagementExcel,
};
